/* Released IDs: never renumber this registry when adding or reordering words. */
const releasedIds: Record<string, Record<string, number>> = {
  "Музыка": {
    "cantante": 1,
    "concierto": 2,
    "entrada": 3,
    "escenario": 4,
    "álbum": 5,
    "canción": 6,
    "gira": 7,
    "ritmo": 8,
    "letra": 9,
    "voz": 10,
    "artista": 11,
    "público": 12,
    "micrófono": 13,
    "estribillo": 14
  },
  "Знакомство и о себе": {
    "hola": 1,
    "adiós": 2,
    "gracias": 3,
    "por favor": 4,
    "sí": 5,
    "no": 6,
    "bien": 7,
    "mal": 8,
    "nombre": 9,
    "apellido": 10,
    "persona": 11,
    "hombre": 12,
    "mujer": 13,
    "chico": 14,
    "chica": 15,
    "amigo": 16,
    "amiga": 17,
    "señor": 18,
    "señora": 19,
    "país": 20,
    "ciudad": 21,
    "pueblo": 22,
    "nacionalidad": 23,
    "idioma": 24,
    "español": 25,
    "inglés": 26,
    "francés": 27,
    "alemán": 28,
    "italiano": 29,
    "ruso": 30,
    "estudiante": 31,
    "profesor": 32,
    "profesora": 33,
    "médico": 34,
    "ingeniero": 35,
    "abogado": 36,
    "diseñador": 37,
    "camarero": 38,
    "trabajo": 39,
    "profesión": 40,
    "ser": 41,
    "llamarse": 42,
    "vivir": 43,
    "trabajar": 44,
    "estudiar": 45,
    "hablar": 46,
    "entender": 47,
    "conocer": 48,
    "saber": 49,
    "tener": 50,
    "yo": 51,
    "tú": 52,
    "él": 53,
    "ella": 54,
    "nosotros": 55,
    "vosotros": 56,
    "ellos": 57,
    "usted": 58,
    "ustedes": 59,
    "mi": 60,
    "tu": 61,
    "su": 62,
    "de": 63,
    "en": 64,
    "con": 65,
    "sin": 66,
    "y": 67,
    "o": 68,
    "pero": 69,
    "también": 70,
    "aquí": 71,
    "allí": 72,
    "dónde": 73,
    "de dónde": 74,
    "cómo": 75,
    "qué": 76,
    "quién": 77,
    "cuál": 78,
    "mucho": 79,
    "poco": 80,
    "bueno": 81,
    "malo": 82,
    "grande": 83,
    "pequeño": 84,
    "joven": 85,
    "mayor": 86,
    "nuevo": 87,
    "simpático": 88,
    "interesante": 89,
    "feliz": 90
  },
  "Семья и люди": {
    "familia": 1,
    "padre": 2,
    "madre": 3,
    "padres": 4,
    "hermano": 5,
    "hermana": 6,
    "hijo": 7,
    "hija": 8,
    "hijos": 9,
    "abuelo": 10,
    "abuela": 11,
    "abuelos": 12,
    "tío": 13,
    "tía": 14,
    "primo": 15,
    "prima": 16,
    "marido": 17,
    "esposa": 18,
    "pareja": 19,
    "novio": 20,
    "novia": 21,
    "bebé": 22,
    "niño": 23,
    "niña": 24,
    "adulto": 25,
    "vecino": 26,
    "vecina": 27,
    "compañero": 28,
    "compañera": 29,
    "parecer": 30,
    "querer": 31,
    "amar": 32,
    "ayudar": 33,
    "alto": 34,
    "bajo": 35,
    "delgado": 36,
    "gordo": 37,
    "guapo": 38,
    "bonito": 39,
    "viejo": 40,
    "rubio": 41,
    "moreno": 42,
    "pelirrojo": 43,
    "pelo": 44,
    "ojo": 45,
    "ojos": 46,
    "cara": 47,
    "nariz": 48,
    "boca": 49,
    "barba": 50,
    "gafas": 51,
    "amable": 52,
    "serio": 53,
    "divertido": 54,
    "tranquilo": 55,
    "nervioso": 56,
    "sociable": 57,
    "tímido": 58,
    "trabajador": 59,
    "perezoso": 60,
    "inteligente": 61,
    "paciente": 62,
    "generoso": 63,
    "cariñoso": 64,
    "mis": 65,
    "tus": 66,
    "sus": 67,
    "nuestro": 68,
    "nuestra": 69,
    "nuestros": 70,
    "nuestras": 71,
    "casado": 72,
    "soltero": 73,
    "divorciado": 74,
    "edad": 75,
    "años": 76,
    "mayor que": 77,
    "menor que": 78,
    "parecido": 79,
    "diferente": 80
  },
  "Мой день и рутина": {
    "día": 1,
    "mañana": 2,
    "tarde": 3,
    "noche": 4,
    "hora": 5,
    "minuto": 6,
    "hoy": 7,
    "ayer": 8,
    "siempre": 9,
    "normalmente": 10,
    "generalmente": 11,
    "a veces": 12,
    "nunca": 13,
    "primero": 14,
    "después": 15,
    "luego": 16,
    "temprano": 17,
    "levantarse": 18,
    "despertarse": 19,
    "ducharse": 20,
    "lavarse": 21,
    "vestirse": 22,
    "desayunar": 23,
    "comer": 24,
    "cenar": 25,
    "empezar": 26,
    "terminar": 27,
    "salir": 28,
    "llegar": 29,
    "volver": 30,
    "descansar": 31,
    "dormir": 32,
    "leer": 33,
    "escribir": 34,
    "ver": 35,
    "escuchar": 36,
    "caminar": 37,
    "correr": 38,
    "cocinar": 39,
    "limpiar": 40,
    "comprar": 41,
    "hacer": 42,
    "ir": 43,
    "venir": 44,
    "casa": 45,
    "escuela": 46,
    "universidad": 47,
    "oficina": 48,
    "desayuno": 49,
    "comida": 50,
    "cena": 51,
    "café": 52,
    "agua": 53,
    "autobús": 54,
    "metro": 55,
    "coche": 56,
    "pie": 57,
    "lunes": 58,
    "martes": 59,
    "miércoles": 60,
    "jueves": 61,
    "viernes": 62,
    "sábado": 63,
    "domingo": 64,
    "semana": 65,
    "fin de semana": 66,
    "a las ocho": 67,
    "a la una": 68,
    "por la mañana": 69,
    "por la tarde": 70,
    "por la noche": 71,
    "antes": 72,
    "después de": 73,
    "durante": 74,
    "desde": 75,
    "hasta": 76,
    "cada día": 77,
    "todos los días": 78,
    "rápido": 79,
    "despacio": 80,
    "ocupado": 81,
    "libre": 82
  },
  "Дом и жильё": {
    "piso": 1,
    "apartamento": 2,
    "habitación": 3,
    "dormitorio": 4,
    "salón": 5,
    "cocina": 6,
    "baño": 7,
    "comedor": 8,
    "balcón": 9,
    "terraza": 10,
    "jardín": 11,
    "puerta": 12,
    "ventana": 13,
    "pared": 14,
    "suelo": 15,
    "techo": 16,
    "escalera": 17,
    "ascensor": 18,
    "llave": 19,
    "mesa": 20,
    "silla": 21,
    "sofá": 22,
    "cama": 23,
    "armario": 24,
    "estantería": 25,
    "escritorio": 26,
    "lámpara": 27,
    "espejo": 28,
    "alfombra": 29,
    "cortina": 30,
    "televisión": 31,
    "nevera": 32,
    "frigorífico": 33,
    "horno": 34,
    "microondas": 35,
    "lavadora": 36,
    "lavavajillas": 37,
    "ducha": 38,
    "bañera": 39,
    "lavabo": 40,
    "inodoro": 41,
    "mueble": 42,
    "cajón": 43,
    "sofá cama": 44,
    "aire acondicionado": 45,
    "calefacción": 46,
    "luz": 47,
    "electricidad": 48,
    "alquiler": 49,
    "alquilar": 50,
    "vender": 51,
    "ordenar": 52,
    "abrir": 53,
    "cerrar": 54,
    "entrar": 55,
    "subir": 56,
    "bajar": 57,
    "cómodo": 58,
    "incómodo": 59,
    "feo": 60,
    "moderno": 61,
    "luminoso": 62,
    "oscuro": 63,
    "limpio": 64,
    "sucio": 65,
    "ruidoso": 66,
    "caro": 67,
    "barato": 68,
    "cerca": 69,
    "lejos": 70,
    "arriba": 71,
    "abajo": 72,
    "dentro": 73,
    "fuera": 74,
    "delante": 75,
    "detrás": 76,
    "al lado de": 77,
    "entre": 78,
    "encima de": 79,
    "debajo de": 80,
    "enfrente de": 81,
    "Hay…": 82,
    "No hay…": 83,
    "Mi casa tiene…": 84,
    "Vivo en un piso.": 85,
    "La cocina es grande.": 86,
    "¿Dónde está el baño?": 87
  },
  "Еда и ресторан": {
    "bebida": 1,
    "almuerzo": 2,
    "pan": 3,
    "arroz": 4,
    "pasta": 5,
    "carne": 6,
    "pollo": 7,
    "pescado": 8,
    "huevo": 9,
    "queso": 10,
    "leche": 11,
    "yogur": 12,
    "mantequilla": 13,
    "aceite": 14,
    "sal": 15,
    "azúcar": 16,
    "fruta": 17,
    "manzana": 18,
    "plátano": 19,
    "naranja": 20,
    "pera": 21,
    "fresa": 22,
    "uva": 23,
    "limón": 24,
    "sandía": 25,
    "verdura": 26,
    "tomate": 27,
    "patata": 28,
    "cebolla": 29,
    "zanahoria": 30,
    "lechuga": 31,
    "pepino": 32,
    "ajo": 33,
    "sopa": 34,
    "ensalada": 35,
    "bocadillo": 36,
    "pizza": 37,
    "hamburguesa": 38,
    "postre": 39,
    "pastel": 40,
    "chocolate": 41,
    "helado": 42,
    "té": 43,
    "zumo": 44,
    "cerveza": 45,
    "vino": 46,
    "botella": 47,
    "vaso": 48,
    "taza": 49,
    "plato": 50,
    "cuchara": 51,
    "tenedor": 52,
    "cuchillo": 53,
    "servilleta": 54,
    "beber": 55,
    "preparar": 56,
    "cortar": 57,
    "probar": 58,
    "pedir": 59,
    "pagar": 60,
    "gustar": 61,
    "tener hambre": 62,
    "tener sed": 63,
    "rico": 64,
    "delicioso": 65,
    "dulce": 66,
    "salado": 67,
    "picante": 68,
    "caliente": 69,
    "frío": 70,
    "fresco": 71,
    "menú": 72,
    "carta": 73,
    "restaurante": 74,
    "cafetería": 75,
    "bar": 76,
    "cuenta": 77,
    "propina": 78,
    "reserva": 79,
    "¿Qué quieres comer?": 80,
    "Quiero una ensalada.": 81,
    "Me gusta el café.": 82,
    "No me gusta el pescado.": 83,
    "Tengo hambre.": 84,
    "Tengo sed.": 85,
    "La cuenta, por favor.": 86,
    "Para mí…": 87,
    "¿Qué recomienda?": 88,
    "Está muy rico.": 89,
    "reservar una mesa": 90,
    "menú del día": 91,
    "primer plato": 92,
    "segundo plato": 93,
    "plato principal": 94,
    "entrante": 95,
    "tapas": 96,
    "ración": 97,
    "agua sin gas": 98,
    "agua con gas": 99,
    "marisco": 100,
    "verduras": 101,
    "camarera": 102,
    "pagar con tarjeta": 103,
    "pagar en efectivo": 104,
    "dividir la cuenta": 105,
    "crudo": 106,
    "bien hecho": 107,
    "al punto": 108,
    "vegetariano": 109,
    "¡Buen provecho!": 110
  },
  "Город и транспорт": {
    "calle": 1,
    "avenida": 2,
    "plaza": 3,
    "barrio": 4,
    "centro": 5,
    "edificio": 6,
    "tienda": 7,
    "supermercado": 8,
    "banco": 9,
    "farmacia": 10,
    "hospital": 11,
    "museo": 12,
    "cine": 13,
    "teatro": 14,
    "hotel": 15,
    "parque": 16,
    "estación": 17,
    "parada": 18,
    "aeropuerto": 19,
    "estación de tren": 20,
    "estación de autobuses": 21,
    "tren": 22,
    "taxi": 23,
    "bicicleta": 24,
    "moto": 25,
    "billete": 26,
    "tarjeta": 27,
    "conductor": 28,
    "pasajero": 29,
    "tráfico": 30,
    "semáforo": 31,
    "cruce": 32,
    "camino": 33,
    "mapa": 34,
    "dirección": 35,
    "conducir": 36,
    "coger": 37,
    "tomar": 38,
    "cruzar": 39,
    "girar": 40,
    "seguir": 41,
    "parar": 42,
    "esperar": 43,
    "preguntar": 44,
    "derecha": 45,
    "izquierda": 46,
    "recto": 47,
    "al lado": 48,
    "enfrente": 49,
    "lento": 50,
    "abierto": 51,
    "cerrado": 52,
    "salida": 53,
    "esquina": 54,
    "norte": 55,
    "sur": 56,
    "este": 57,
    "oeste": 58,
    "centro histórico": 59,
    "zona": 60,
    "puente": 61,
    "río": 62,
    "carretera": 63,
    "autopista": 64,
    "¿Dónde está…?": 65,
    "¿Cómo llego a…?": 66,
    "Sigue recto.": 67,
    "Gira a la derecha.": 68,
    "Gira a la izquierda.": 69,
    "Está cerca.": 70,
    "Está lejos.": 71,
    "Voy en metro.": 72,
    "Voy a pie.": 73,
    "¿Qué autobús necesito?": 74
  },
  "Покупки и одежда": {
    "centro comercial": 1,
    "mercado": 2,
    "ropa": 3,
    "camiseta": 4,
    "camisa": 5,
    "blusa": 6,
    "jersey": 7,
    "chaqueta": 8,
    "abrigo": 9,
    "vestido": 10,
    "falda": 11,
    "pantalón": 12,
    "vaqueros": 13,
    "pantalones cortos": 14,
    "traje": 15,
    "zapato": 16,
    "zapatillas": 17,
    "botas": 18,
    "sandalias": 19,
    "calcetines": 20,
    "sombrero": 21,
    "gorra": 22,
    "bufanda": 23,
    "guantes": 24,
    "bolso": 25,
    "mochila": 26,
    "cinturón": 27,
    "talla": 28,
    "color": 29,
    "rojo": 30,
    "azul": 31,
    "verde": 32,
    "amarillo": 33,
    "negro": 34,
    "blanco": 35,
    "gris": 36,
    "marrón": 37,
    "rosa": 38,
    "morado": 39,
    "costar": 40,
    "probarse": 41,
    "llevar": 42,
    "buscar": 43,
    "encontrar": 44,
    "necesitar": 45,
    "elegir": 46,
    "cambiar": 47,
    "devolver": 48,
    "precio": 49,
    "dinero": 50,
    "efectivo": 51,
    "descuento": 52,
    "oferta": 53,
    "rebajas": 54,
    "caja": 55,
    "recibo": 56,
    "ticket": 57,
    "dependiente": 58,
    "cliente": 59,
    "probador": 60,
    "largo": 61,
    "corto": 62,
    "ancho": 63,
    "estrecho": 64,
    "usado": 65,
    "talla pequeña": 66,
    "talla mediana": 67,
    "talla grande": 68,
    "¿Cuánto cuesta?": 69,
    "¿Cuánto cuestan?": 70,
    "Es muy caro.": 71,
    "¿Tiene otra talla?": 72,
    "¿Tiene otro color?": 73,
    "Quiero probarme esto.": 74,
    "Me queda bien.": 75,
    "Me queda grande.": 76,
    "Me queda pequeño.": 77,
    "Solo estoy mirando.": 78,
    "Me lo llevo.": 79,
    "Pago con tarjeta.": 80,
    "Pago en efectivo.": 81,
    "¿Dónde está la caja?": 82,
    "¿Puedo cambiarlo?": 83,
    "¿Puedo devolverlo?": 84
  },
  "Путешествия": {
    "viaje": 1,
    "viajar": 2,
    "vacaciones": 3,
    "turista": 4,
    "destino": 5,
    "avión": 6,
    "vuelo": 7,
    "barco": 8,
    "pasaporte": 9,
    "documento": 10,
    "maleta": 11,
    "equipaje": 12,
    "tarjeta de embarque": 13,
    "terminal": 14,
    "asiento": 15,
    "ventanilla": 16,
    "pasillo": 17,
    "llegada": 18,
    "retraso": 19,
    "cancelación": 20,
    "recepción": 21,
    "recepcionista": 22,
    "reservar": 23,
    "cancelar": 24,
    "confirmar": 25,
    "volar": 26,
    "visitar": 27,
    "quedarse": 28,
    "alojarse": 29,
    "hacer la maleta": 30,
    "facturar": 31,
    "embarcar": 32,
    "aterrizar": 33,
    "despegar": 34,
    "guía": 35,
    "excursión": 36,
    "playa": 37,
    "montaña": 38,
    "mar": 39,
    "monumento": 40,
    "foto": 41,
    "cámara": 42,
    "recuerdo": 43,
    "extranjero": 44,
    "local": 45,
    "ida": 46,
    "vuelta": 47,
    "ida y vuelta": 48,
    "directo": 49,
    "escala": 50,
    "disponible": 51,
    "completo": 52,
    "perdido": 53,
    "¿Dónde está la puerta…?": 54,
    "¿A qué hora sale el vuelo?": 55,
    "¿A qué hora llega?": 56,
    "Tengo una reserva.": 57,
    "Quiero reservar una habitación.": 58,
    "Una habitación para dos personas.": 59,
    "¿El desayuno está incluido?": 60,
    "¿Dónde recojo el equipaje?": 61,
    "He perdido mi maleta.": 62,
    "Quiero un billete a Madrid.": 63,
    "Solo ida.": 64,
    "Ida y vuelta.": 65,
    "¿Hay wifi?": 66,
    "¿A qué hora es el check-out?": 67,
    "Necesito un taxi.": 68,
    "Estoy de vacaciones.": 69,
    "Buen viaje.": 70,
    "ruta": 71,
    "recorrido": 72,
    "billete de ida y vuelta": 73,
    "embarque": 74,
    "puerta de embarque": 75,
    "equipaje de mano": 76,
    "visado": 77,
    "aduana": 78,
    "frontera": 79,
    "alojamiento": 80,
    "hacer el registro de entrada": 81,
    "hacer el check-in": 82,
    "hacer el registro de salida": 83,
    "hacer el check-out": 84,
    "alquilar un coche": 85,
    "carné de conducir": 86,
    "centro de la ciudad": 87,
    "lugar de interés": 88,
    "atracción turística": 89,
    "visita guiada": 90,
    "perderse": 91
  },
  "Работа и учёба": {
    "empleo": 1,
    "empresa": 2,
    "jefe": 3,
    "jefa": 4,
    "reunión": 5,
    "proyecto": 6,
    "tarea": 7,
    "correo": 8,
    "ordenador": 9,
    "informe": 10,
    "horario": 11,
    "sueldo": 12,
    "instituto": 13,
    "clase": 14,
    "curso": 15,
    "examen": 16,
    "ejercicio": 17,
    "deberes": 18,
    "libro": 19,
    "cuaderno": 20,
    "bolígrafo": 21,
    "lápiz": 22,
    "papel": 23,
    "pregunta": 24,
    "respuesta": 25,
    "nota": 26,
    "aprender": 27,
    "enseñar": 28,
    "explicar": 29,
    "responder": 30,
    "recordar": 31,
    "olvidar": 32,
    "practicar": 33,
    "enviar": 34,
    "recibir": 35,
    "llamar": 36,
    "organizar": 37,
    "presentar": 38,
    "aprobar": 39,
    "suspender": 40,
    "fácil": 41,
    "difícil": 42,
    "importante": 43,
    "aburrido": 44,
    "correcto": 45,
    "incorrecto": 46,
    "preparado": 47,
    "tiempo completo": 48,
    "media jornada": 49,
    "experiencia": 50,
    "entrevista": 51,
    "currículum": 52,
    "contrato": 53,
    "puesto": 54,
    "equipo": 55,
    "objetivo": 56,
    "resultado": 57,
    "descanso": 58,
    "¿A qué te dedicas?": 59,
    "Trabajo en una empresa.": 60,
    "Soy estudiante.": 61,
    "Estudio español.": 62,
    "Tengo una reunión.": 63,
    "Tengo un examen mañana.": 64,
    "No entiendo.": 65,
    "¿Puedes repetir?": 66,
    "¿Qué significa…?": 67,
    "Tengo que estudiar.": 68,
    "Trabajo desde casa.": 69,
    "Estoy buscando trabajo.": 70
  },
  "Здоровье": {
    "cuerpo": 1,
    "cabeza": 2,
    "oreja": 3,
    "diente": 4,
    "cuello": 5,
    "hombro": 6,
    "brazo": 7,
    "mano": 8,
    "dedo": 9,
    "pecho": 10,
    "espalda": 11,
    "estómago": 12,
    "barriga": 13,
    "pierna": 14,
    "rodilla": 15,
    "corazón": 16,
    "sangre": 17,
    "salud": 18,
    "doctora": 19,
    "enfermero": 20,
    "enfermera": 21,
    "clínica": 22,
    "medicamento": 23,
    "pastilla": 24,
    "receta": 25,
    "dolor": 26,
    "fiebre": 27,
    "tos": 28,
    "resfriado": 29,
    "gripe": 30,
    "alergia": 31,
    "herida": 32,
    "enfermedad": 33,
    "síntoma": 34,
    "cita": 35,
    "seguro": 36,
    "doler": 37,
    "sentirse": 38,
    "estar": 39,
    "respirar": 40,
    "mejorar": 41,
    "empeorar": 42,
    "curarse": 43,
    "sano": 44,
    "enfermo": 45,
    "cansado": 46,
    "débil": 47,
    "fuerte": 48,
    "mareado": 49,
    "mejor": 50,
    "peor": 51,
    "desde ayer": 52,
    "urgente": 53,
    "emergencia": 54,
    "ambulancia": 55,
    "temperatura": 56,
    "presión": 57,
    "análisis": 58,
    "tratamiento": 59,
    "dolor de cabeza": 60,
    "dolor de garganta": 61,
    "dolor de espalda": 62,
    "dolor de estómago": 63,
    "Tengo fiebre.": 64,
    "Me duele la cabeza.": 65,
    "Me duele el estómago.": 66,
    "No me siento bien.": 67,
    "Estoy cansado.": 68,
    "Tengo tos.": 69,
    "Tengo alergia.": 70,
    "Necesito un médico.": 71,
    "¿Dónde está la farmacia?": 72,
    "¿Tiene cita?": 73,
    "Tome esta medicina.": 74,
    "Descanse.": 75,
    "Que te mejores.": 76
  },
  "Досуг и хобби": {
    "tiempo libre": 1,
    "hobby": 2,
    "deporte": 3,
    "fútbol": 4,
    "tenis": 5,
    "baloncesto": 6,
    "natación": 7,
    "gimnasio": 8,
    "música": 9,
    "guitarra": 10,
    "piano": 11,
    "película": 12,
    "serie": 13,
    "novela": 14,
    "revista": 15,
    "periódico": 16,
    "fotografía": 17,
    "videojuego": 18,
    "juego": 19,
    "internet": 20,
    "redes sociales": 21,
    "fiesta": 22,
    "paseo": 23,
    "jugar": 24,
    "bailar": 25,
    "cantar": 26,
    "tocar": 27,
    "dibujar": 28,
    "pintar": 29,
    "nadar": 30,
    "entrenar": 31,
    "quedar": 32,
    "disfrutar": 33,
    "divertirse": 34,
    "encantar": 35,
    "preferir": 36,
    "poder": 37,
    "favorito": 38,
    "solo": 39,
    "juntos": 40,
    "¿Qué haces en tu tiempo libre?": 41,
    "Me gusta leer.": 42,
    "Me encanta viajar.": 43,
    "Juego al fútbol.": 44,
    "Escucho música.": 45,
    "Veo series.": 46,
    "Voy al gimnasio.": 47,
    "Salgo con amigos.": 48,
    "¿Quieres venir?": 49,
    "¿Quedamos mañana?": 50,
    "No puedo hoy.": 51,
    "Prefiero quedarme en casa.": 52,
    "¿Cuál es tu película favorita?": 53,
    "Me gusta mucho.": 54,
    "No me gusta nada.": 55,
    "Lo paso bien.": 56
  },
  "Погода и природа": {
    "tiempo": 1,
    "clima": 2,
    "sol": 3,
    "lluvia": 4,
    "nieve": 5,
    "viento": 6,
    "nube": 7,
    "tormenta": 8,
    "niebla": 9,
    "calor": 10,
    "grado": 11,
    "primavera": 12,
    "verano": 13,
    "otoño": 14,
    "invierno": 15,
    "enero": 16,
    "febrero": 17,
    "marzo": 18,
    "abril": 19,
    "mayo": 20,
    "junio": 21,
    "julio": 22,
    "agosto": 23,
    "septiembre": 24,
    "octubre": 25,
    "noviembre": 26,
    "diciembre": 27,
    "naturaleza": 28,
    "océano": 29,
    "lago": 30,
    "bosque": 31,
    "campo": 32,
    "isla": 33,
    "árbol": 34,
    "planta": 35,
    "flor": 36,
    "hierba": 37,
    "tierra": 38,
    "cielo": 39,
    "estrella": 40,
    "luna": 41,
    "animal": 42,
    "perro": 43,
    "gato": 44,
    "pájaro": 45,
    "pez": 46,
    "caballo": 47,
    "vaca": 48,
    "oveja": 49,
    "hacer sol": 50,
    "llover": 51,
    "nevar": 52,
    "hacer frío": 53,
    "hacer calor": 54,
    "hacer viento": 55,
    "estar nublado": 56,
    "seco": 57,
    "húmedo": 58,
    "soleado": 59,
    "nublado": 60,
    "lluvioso": 61,
    "nevado": 62,
    "natural": 63,
    "contaminado": 64,
    "esta semana": 65,
    "¿Qué tiempo hace?": 66,
    "Hace sol.": 67,
    "Hace frío.": 68,
    "Hace calor.": 69,
    "Hace viento.": 70,
    "Está nublado.": 71,
    "Llueve.": 72,
    "Nieva.": 73,
    "Hace 20 grados.": 74,
    "¿Qué temperatura hace?": 75,
    "Me gusta el verano.": 76,
    "En invierno hace frío.": 77,
    "Mañana va a llover.": 78
  },
  "Ночная жизнь": {
    "vida nocturna": 1,
    "salir de fiesta": 2,
    "pub": 3,
    "discoteca": 4,
    "club": 5,
    "baile": 6,
    "DJ": 7,
    "disyóquey": 8,
    "música en directo": 9,
    "tomar algo": 10,
    "copa de vino": 11,
    "copa": 12,
    "cóctel": 13,
    "chupito": 14,
    "barra": 15,
    "entrada gratuita": 16,
    "cola": 17,
    "portero": 18,
    "personal de seguridad": 19,
    "DNI": 20,
    "documento de identidad": 21,
    "pista de baile": 22,
    "conocer a alguien": 23,
    "ligar": 24,
    "invitar a una copa": 25,
    "invitar": 26,
    "ronda": 27,
    "brindis": 28,
    "brindar": 29,
    "abarrotado": 30,
    "ambiente": 31,
    "resaca": 32,
    "estar borracho": 33,
    "despejarse": 34,
    "volver a casa": 35,
    "seguir de fiesta": 36,
    "juerga": 37
  },
  "Живой сленг": {
    "guay": 1,
    "¡Qué guay!": 2,
    "chaval": 3,
    "chavala": 4,
    "colega": 5,
    "peña": 6,
    "currar": 7,
    "curro": 8,
    "molar": 9,
    "flipar": 10,
    "estoy flipando": 11,
    "rollo": 12,
    "movida": 13,
    "follón": 14,
    "jaleo": 15,
    "lío": 16,
    "montarla": 17,
    "no pasa nada": 18,
    "¡Venga ya!": 19,
    "¡Venga!": 20,
    "claro": 21,
    "vale": 22,
    "en plan": 23,
    "de verdad": 24,
    "¿En serio?": 25,
    "ni de broma": 26,
    "es broma": 27,
    "ni idea": 28,
    "me da igual": 29,
    "como quieras": 30,
    "estoy harto": 31,
    "harta": 32,
    "tontería": 33,
    "tonto": 34,
    "tonta": 35,
    "¡Joder!": 36,
    "de puta madre": 37,
    "fatal": 38,
    "genial": 39,
    "qué fuerte": 40,
    "qué horror": 41,
    "qué vergüenza": 42,
    "me da pereza": 43,
    "déjame en paz": 44,
    "tranqui": 45,
    "un segundo": 46,
    "pasarlo genial": 47
  },
  "Знакомства и отношения": {
    "conocerse": 1,
    "coquetear": 2,
    "enamorarse": 3,
    "estar enamorado": 4,
    "amor": 5,
    "amor a primera vista": 6,
    "flechazo": 7,
    "exnovio": 8,
    "ex": 9,
    "exnovia": 10,
    "casada": 11,
    "relación": 12,
    "relación seria": 13,
    "relación abierta": 14,
    "monógamo": 15,
    "salir con alguien": 16,
    "estar juntos": 17,
    "besar": 18,
    "beso": 19,
    "abrazar": 20,
    "abrazo": 21,
    "atractivo": 22,
    "mono": 23,
    "química": 24,
    "tener cosas en común": 25,
    "interesarse por alguien": 26,
    "declararse": 27,
    "invitar a salir": 28,
    "rechazar": 29,
    "romper": 30,
    "ruptura": 31,
    "discutir": 32,
    "reñir": 33,
    "reconciliarse": 34,
    "estar celoso": 35,
    "celos": 36,
    "ser infiel": 37,
    "confiar": 38,
    "echar de menos a alguien": 39,
    "irse a vivir juntos": 40
  },
  "Переписка и интернет": {
    "mensaje": 1,
    "escribir un mensaje": 2,
    "mandar": 3,
    "contestar": 4,
    "chat": 5,
    "chatear": 6,
    "móvil": 7,
    "teléfono": 8,
    "número de teléfono": 9,
    "contacto": 10,
    "guardar el número": 11,
    "llamada": 12,
    "llamada perdida": 13,
    "contestar una llamada": 14,
    "devolver la llamada": 15,
    "videollamada": 16,
    "mensaje de voz": 17,
    "audio": 18,
    "emoji": 19,
    "emoticono": 20,
    "vídeo": 21,
    "enlace": 22,
    "reenviar": 23,
    "borrar": 24,
    "eliminar": 25,
    "bloquear": 26,
    "desbloquear": 27,
    "silenciar": 28,
    "notificación": 29,
    "grupo": 30,
    "añadir al grupo": 31,
    "salir del grupo": 32,
    "en línea": 33,
    "conectado": 34,
    "desconectado": 35,
    "leído": 36,
    "dejar en visto": 37,
    "está escribiendo…": 38,
    "errata": 39,
    "autocorrector": 40,
    "wifi": 41,
    "contraseña": 42,
    "cargador": 43,
    "batería": 44,
    "quedarse sin batería": 45,
    "estar en contacto": 46
  }
};

export function vocabularyId(topic: string, spanish: string): number {
  const released = releasedIds[topic]?.[spanish];
  if (released !== undefined) return released;
  const input = topic.normalize('NFC') + ':' + spanish.normalize('NFC').trim().toLowerCase();
  let hash = 2166136261;
  for (const letter of input) { hash ^= letter.codePointAt(0)!; hash = Math.imul(hash, 16777619); }
  return 10000000000 + (hash >>> 0);
}

const releasedOwners = new Map(Object.entries(releasedIds).flatMap(([topic, words]) =>
  Object.keys(words).map((word) => [word.normalize('NFC').trim().toLowerCase(), topic] as const)));
export const releasedVocabularyTopic = (spanish: string) =>
  releasedOwners.get(spanish.normalize('NFC').trim().toLowerCase());
