export type A2VocabularyEntry = {
  id: number;
  es: string;
  ru: string;
  example: string;
  exampleRu: string;
};

export type A2VocabularyTopic = {
  name: string;
  icon: string;
  entries: A2VocabularyEntry[];
};

type Row = [es: string, ru: string, example: string, exampleRu: string];

const topic = (name: string, icon: string, rows: Row[]): A2VocabularyTopic => ({
  name,
  icon,
  entries: rows.map(([es, ru, example, exampleRu], index) => ({
    id: index + 1,
    es,
    ru,
    example,
    exampleRu,
  })),
});

export const a2VocabularyTopics: A2VocabularyTopic[] = [
  topic('Время, даты и планы', '📅', [
    ['fecha', 'дата', 'Escribe la fecha de hoy en el formulario.', 'Напиши сегодняшнюю дату в анкете.'],
    ['calendario', 'календарь', 'He marcado la reunión en el calendario.', 'Я отметил встречу в календаре.'],
    ['agenda', 'ежедневник', 'Tengo la dirección apuntada en mi agenda.', 'Адрес записан у меня в ежедневнике.'],
    ['plazo', 'срок', 'El plazo termina el próximo viernes.', 'Срок заканчивается в следующую пятницу.'],
    ['puntual', 'пунктуальный', 'Ana siempre es puntual y llega cinco minutos antes.', 'Ана всегда пунктуальна и приходит на пять минут раньше.'],
    ['pendiente', 'незавершённый', 'Todavía tengo una llamada pendiente.', 'Мне ещё нужно совершить один звонок.'],
    ['quedar', 'договариваться о встрече', 'Podemos quedar delante del cine a las siete.', 'Мы можем договориться встретиться перед кинотеатром в семь.'],
    ['aplazar', 'откладывать', 'Tenemos que aplazar la visita hasta el lunes.', 'Нам нужно отложить визит до понедельника.'],
    ['posponer', 'переносить', 'Decidieron posponer el viaje por la lluvia.', 'Они решили перенести поездку из-за дождя.'],
    ['confirmar', 'подтверждать', 'Necesito confirmar la hora de la cita.', 'Мне нужно подтвердить время встречи.'],
    ['planear', 'планировать', 'Vamos a planear las vacaciones este fin de semana.', 'Мы собираемся спланировать отпуск в эти выходные.'],
    ['durar', 'длиться', 'El curso suele durar tres meses.', 'Курс обычно длится три месяца.'],
    ['tardar', 'занимать время', 'El autobús tarda media hora en llegar.', 'Автобусу требуется полчаса, чтобы приехать.'],
    ['próximo', 'следующий', 'El próximo tren sale a las nueve.', 'Следующий поезд отправляется в девять.'],
    ['anterior', 'предыдущий', 'Puedes consultar el mensaje anterior.', 'Ты можешь посмотреть предыдущее сообщение.'],
    ['mensual', 'ежемесячный', 'Pago una cuota mensual por el gimnasio.', 'Я ежемесячно плачу за спортзал.'],
    ['diario', 'ежедневный', 'Un paseo diario me ayuda a descansar.', 'Ежедневная прогулка помогает мне отдохнуть.'],
    ['dentro de', 'через', 'La película empieza dentro de diez minutos.', 'Фильм начнётся через десять минут.'],
    ['desde hace', 'уже в течение', 'Vivo aquí desde hace dos años.', 'Я живу здесь уже два года.'],
    ['a tiempo', 'вовремя', 'Llegamos a tiempo para ver el principio de la película.', 'Мы пришли вовремя и увидели начало фильма.'],
    ['con antelación', 'заранее', 'Conviene reservar la mesa con antelación.', 'Столик лучше забронировать заранее.'],
    ['tener previsto', 'планировать', 'Tengo previsto visitar Sevilla en abril.', 'Я планирую посетить Севилью в апреле.'],
    ['medianoche', 'полночь', 'El último tren sale a medianoche.', 'Последний поезд отправляется в полночь.'],
    ['mediodía', 'полдень', 'Nos vemos delante del museo al mediodía.', 'Встретимся перед музеем в полдень.'],
    ['madrugada', 'раннее утро', 'Nuestro vuelo sale de madrugada.', 'Наш рейс вылетает рано утром.'],
    ['víspera', 'канун', 'Hicimos las maletas la víspera del viaje.', 'Мы собрали чемоданы накануне поездки.'],
    ['trimestre', 'триместр', 'El primer trimestre termina en diciembre.', 'Первый триместр заканчивается в декабре.'],
    ['semestre', 'семестр', 'Este semestre tengo cinco asignaturas.', 'В этом семестре у меня пять предметов.'],
    ['temporada', 'сезон', 'La piscina abre durante la temporada de verano.', 'Бассейн открыт в летний сезон.'],
    ['evento', 'мероприятие', 'El evento empieza a las seis de la tarde.', 'Мероприятие начинается в шесть вечера.'],
    ['adelantar', 'переносить на более раннее время', '¿Podemos adelantar la reunión a las diez?', 'Мы можем перенести встречу на десять часов?'],
    ['avisar con tiempo', 'предупреждать заранее', 'Avísame con tiempo si no puedes venir.', 'Предупреди меня заранее, если не сможешь прийти.'],
    ['tener tiempo', 'иметь время', 'Esta tarde tengo tiempo para ir al banco.', 'Сегодня днём у меня есть время сходить в банк.'],
    ['estar libre', 'быть свободным', '¿Estás libre el sábado por la mañana?', 'Ты свободен в субботу утром?'],
    ['estar ocupado', 'быть занятым', 'Estaré ocupado hasta las cinco.', 'Я буду занят до пяти часов.'],
    ['cuanto antes', 'как можно скорее', 'Necesito confirmar la reserva cuanto antes.', 'Мне нужно подтвердить бронирование как можно скорее.'],
    ['a partir de', 'начиная с', 'Puedes recoger el paquete a partir del lunes.', 'Ты можешь забрать посылку начиная с понедельника.'],
    ['hasta entonces', 'до тех пор', 'La cita es el viernes; hasta entonces, prepara los documentos.', 'Встреча в пятницу, а до тех пор подготовь документы.'],
    ['a última hora', 'в последний момент', 'Cancelaron el concierto a última hora.', 'Концерт отменили в последний момент.'],
    ['de vez en cuando', 'время от времени', 'De vez en cuando cenamos fuera de casa.', 'Время от времени мы ужинаем вне дома.'],
    ['fin de mes', 'конец месяца', 'Tengo que pagar el alquiler a fin de mes.', 'Мне нужно заплатить за аренду в конце месяца.'],
    ['el día anterior', 'предыдущий день', 'Recibí la confirmación el día anterior.', 'Я получил подтверждение накануне.'],
  ]),
  topic('Услуги и документы', '🏛️', [
    ['ayuntamiento', 'мэрия', 'El ayuntamiento está junto a la plaza principal.', 'Мэрия находится рядом с главной площадью.'],
    ['comisaría', 'полицейский участок', 'Fuimos a la comisaría para denunciar el robo.', 'Мы пошли в полицейский участок, чтобы заявить о краже.'],
    ['oficina de correos', 'почтовое отделение', 'La oficina de correos cierra a las ocho.', 'Почтовое отделение закрывается в восемь.'],
    ['ventanilla', 'окно обслуживания', 'Pregunte en la ventanilla número cuatro.', 'Спросите в окне номер четыре.'],
    ['formulario', 'анкета', 'Debe completar este formulario con sus datos.', 'Вы должны заполнить эту анкету своими данными.'],
    ['solicitud', 'заявление', 'Presenté la solicitud por internet.', 'Я подал заявление через интернет.'],
    ['trámite', 'официальная процедура', 'Este trámite se puede hacer en línea.', 'Эту официальную процедуру можно пройти онлайн.'],
    ['certificado', 'справка', 'Necesito un certificado para la universidad.', 'Мне нужна справка для университета.'],
    ['permiso', 'разрешение', 'Hace falta un permiso para aparcar aquí.', 'Чтобы парковаться здесь, нужно разрешение.'],
    ['carnet', 'удостоверение', 'No olvides llevar tu carnet de estudiante.', 'Не забудь взять студенческое удостоверение.'],
    ['firma', 'подпись', 'Falta su firma al final del documento.', 'В конце документа не хватает вашей подписи.'],
    ['copia', 'копия', 'Traiga una copia del pasaporte.', 'Принесите копию паспорта.'],
    ['original', 'оригинал', 'El banco necesita ver el documento original.', 'Банку нужно увидеть оригинал документа.'],
    ['sello', 'марка', 'Necesito un sello para enviar esta carta.', 'Мне нужна марка, чтобы отправить это письмо.'],
    ['sobre', 'конверт', 'Escribí la dirección en el sobre.', 'Я написал адрес на конверте.'],
    ['paquete', 'посылка', 'El paquete llegará mañana por la mañana.', 'Посылка прибудет завтра утром.'],
    ['cola', 'очередь', 'Hay una cola larga delante de la caja.', 'Перед кассой длинная очередь.'],
    ['turno', 'номер очереди', 'Coja un turno y espere hasta que lo llamen.', 'Возьмите номерок и ждите, пока вас вызовут.'],
    ['cuenta bancaria', 'банковский счёт', 'Quiero abrir una cuenta bancaria.', 'Я хочу открыть банковский счёт.'],
    ['cajero automático', 'банкомат', 'Hay un cajero automático al otro lado de la calle.', 'На другой стороне улицы есть банкомат.'],
    ['ingresar', 'вносить деньги', 'Voy a ingresar cien euros en mi cuenta.', 'Я собираюсь внести сто евро на свой счёт.'],
    ['retirar', 'снимать деньги', 'Necesito retirar dinero antes del viaje.', 'Мне нужно снять деньги перед поездкой.'],
    ['rellenar', 'заполнять', 'Puede rellenar el impreso con bolígrafo azul.', 'Вы можете заполнить бланк синей ручкой.'],
    ['firmar', 'подписывать', 'Lea el contrato antes de firmar.', 'Прочитайте договор, прежде чем подписывать.'],
    ['renovar', 'продлевать', 'Tengo que renovar el pasaporte este mes.', 'В этом месяце мне нужно продлить паспорт.'],
    ['solicitar', 'запрашивать', 'Puede solicitar una cita por teléfono.', 'Вы можете записаться на приём по телефону.'],
    ['entregar', 'сдавать', 'Debes entregar los documentos antes del viernes.', 'Ты должен сдать документы до пятницы.'],
    ['recoger', 'забирать', 'Puede recoger su tarjeta a partir del lunes.', 'Вы можете забрать свою карту начиная с понедельника.'],
    ['atender', 'обслуживать', 'Ahora están atendiendo al número veintitrés.', 'Сейчас обслуживают номер двадцать три.'],
    ['dato personal', 'личные данные', 'No compartas ningún dato personal por teléfono.', 'Не сообщай личные данные по телефону.'],
    ['dirección postal', 'почтовый адрес', 'Escriba su dirección postal en esta casilla.', 'Напишите свой почтовый адрес в этом поле.'],
    ['código postal', 'почтовый индекс', 'El código postal aparece al final de la dirección.', 'Почтовый индекс указан в конце адреса.'],
    ['documento caducado', 'просроченный документ', 'No puede viajar con un documento caducado.', 'Нельзя путешествовать с просроченным документом.'],
    ['documento vigente', 'действующий документ', 'Para el trámite necesita un documento vigente.', 'Для этой процедуры нужен действующий документ.'],
    ['tasa', 'пошлина', 'La tasa se puede pagar con tarjeta.', 'Пошлину можно оплатить картой.'],
    ['cita previa', 'предварительная запись', 'Para renovar el carnet hace falta cita previa.', 'Для продления удостоверения нужна предварительная запись.'],
    ['pagar una tasa', 'оплачивать пошлину', 'Debe pagar una tasa antes de presentar la solicitud.', 'Перед подачей заявления необходимо оплатить пошлину.'],
    ['presentar documentos', 'подавать документы', 'Puede presentar los documentos en cualquier ventanilla.', 'Вы можете подать документы в любом окне обслуживания.'],
    ['hacer una copia', 'делать копию', 'Voy a hacer una copia de cada página del contrato.', 'Я сделаю копию каждой страницы договора.'],
    ['enviar por correo', 'отправлять по почте', 'Le enviaremos el certificado por correo.', 'Мы отправим вам справку по почте.'],
    ['comprobar la identidad', 'проверять личность', 'El empleado debe comprobar la identidad del cliente.', 'Сотрудник должен проверить личность клиента.'],
    ['número de referencia', 'регистрационный номер', 'Guarde el número de referencia de su solicitud.', 'Сохраните регистрационный номер своего заявления.'],
    ['justificante', 'подтверждающий документ', 'Conserve el justificante de pago.', 'Сохраните подтверждение оплаты.'],
    ['devolución', 'возврат денег', 'La devolución llegará a su cuenta en tres días.', 'Возврат поступит на ваш счёт через три дня.'],
    ['reclamación', 'претензия', 'Presenté una reclamación por el cobro incorrecto.', 'Я подал претензию из-за неправильного списания.'],
    ['oficina de atención', 'центр обслуживания', 'La oficina de atención abre de lunes a viernes.', 'Центр обслуживания открыт с понедельника по пятницу.'],
    ['servicio de atención al cliente', 'служба поддержки клиентов', 'Llame al servicio de atención al cliente para cambiar la reserva.', 'Позвоните в службу поддержки клиентов, чтобы изменить бронирование.'],
    ['darse de alta', 'зарегистрироваться', 'Puede darse de alta en el servicio desde la aplicación.', 'Вы можете зарегистрироваться в сервисе через приложение.'],
    ['dar de baja', 'отказаться от услуги', 'Quiero dar de baja el servicio de internet.', 'Я хочу отказаться от услуги доступа в интернет.'],
  ]),
  topic('Биография и события жизни', '🧭', [
    ['nacer', 'рождаться', 'Mi abuelo tuvo la suerte de nacer en un pueblo pequeño cerca de León.', 'Моему дедушке повезло родиться в маленьком городке недалеко от Леона.'],
    ['crecer', 'расти', 'Me gustaría crecer cerca del mar.', 'Мне хотелось бы расти рядом с морем.'],
    ['infancia', 'детство', 'Durante mi infancia pasaba los veranos con mis abuelos.', 'В детстве я проводил лето с бабушкой и дедушкой.'],
    ['adolescencia', 'подростковый возраст', 'En la adolescencia empezó a tocar la guitarra.', 'В подростковом возрасте он начал играть на гитаре.'],
    ['juventud', 'молодость', 'Mi abuela viajó mucho durante su juventud.', 'Моя бабушка много путешествовала в молодости.'],
    ['mudarse', 'переезжать', 'La familia decidió mudarse a un barrio más tranquilo.', 'Семья решила переехать в более тихий район.'],
    ['graduarse', 'заканчивать учебное заведение', 'Laura espera graduarse el próximo año.', 'Лаура надеется окончить учебное заведение в следующем году.'],
    ['conseguir trabajo', 'найти работу', 'Después del curso pudo conseguir trabajo en un hotel.', 'После курса он смог найти работу в отеле.'],
    ['cambiar de trabajo', 'сменить работу', 'Quiero cambiar de trabajo porque necesito un horario mejor.', 'Я хочу сменить работу, потому что мне нужен более удобный график.'],
    ['enamorarse', 'влюбляться', 'No esperaba enamorarse durante aquel viaje.', 'Он не ожидал влюбиться во время той поездки.'],
    ['casarse', 'жениться', 'Marta y Luis van a casarse en septiembre.', 'Марта и Луис собираются пожениться в сентябре.'],
    ['separarse', 'расставаться', 'Decidieron separarse después de diez años juntos.', 'Они решили расстаться после десяти лет совместной жизни.'],
    ['tener hijos', 'заводить детей', 'Les gustaría tener hijos en el futuro.', 'В будущем они хотели бы завести детей.'],
    ['jubilarse', 'выходить на пенсию', 'Mi padre piensa jubilarse a los sesenta y cinco años.', 'Мой отец планирует выйти на пенсию в шестьдесят пять лет.'],
    ['fallecer', 'скончаться', 'El escritor falleció lejos de su país.', 'Писатель скончался вдали от своей страны.'],
    ['experiencia', 'опыт', 'Vivir en otro país fue una experiencia importante.', 'Жизнь в другой стране стала важным опытом.'],
    ['recuerdo', 'воспоминание', 'Guardo un buen recuerdo de mi primera profesora.', 'У меня сохранилось хорошее воспоминание о первой учительнице.'],
    ['etapa', 'этап', 'La universidad fue una etapa muy feliz de su vida.', 'Университет был очень счастливым этапом его жизни.'],
    ['época', 'период', 'En aquella época no teníamos internet en casa.', 'В тот период у нас дома не было интернета.'],
    ['acontecimiento', 'событие', 'La boda fue el acontecimiento más importante del verano.', 'Свадьба была самым важным событием лета.'],
    ['ocurrir', 'происходить', 'Nadie sabía qué podía ocurrir después.', 'Никто не знал, что могло произойти потом.'],
    ['suceder', 'случаться', 'Algo parecido puede suceder en cualquier familia.', 'Нечто подобное может случиться в любой семье.'],
    ['recordar', 'вспоминать', 'Me gusta recordar los viajes que hicimos juntos.', 'Мне нравится вспоминать поездки, которые мы совершили вместе.'],
    ['olvidarse de', 'забывать о', 'Es fácil olvidarse de la fecha si no la apuntas.', 'Легко забыть о дате, если её не записать.'],
    ['por primera vez', 'впервые', 'Vi el mar por primera vez cuando tenía seis años.', 'Я впервые увидел море, когда мне было шесть лет.'],
    ['desde entonces', 'с тех пор', 'Nos conocimos en 2018 y somos amigos desde entonces.', 'Мы познакомились в 2018 году и с тех пор дружим.'],
  ]),
  topic('Эмоции и мнение', '💭', [
    ['alegría', 'радость', 'La noticia llenó de alegría a toda la familia.', 'Новость наполнила радостью всю семью.'],
    ['tristeza', 'грусть', 'Sintió tristeza al despedirse de sus amigos.', 'Он почувствовал грусть, прощаясь с друзьями.'],
    ['miedo', 'страх', 'Me da miedo volar cuando hay tormenta.', 'Мне страшно летать во время грозы.'],
    ['vergüenza', 'смущение', 'Me da vergüenza hablar delante de mucha gente.', 'Я стесняюсь говорить перед большим количеством людей.'],
    ['sorpresa', 'удивление', 'Su visita fue una sorpresa para todos.', 'Его визит стал сюрпризом для всех.'],
    ['preocupación', 'беспокойство', 'Su retraso nos causó mucha preocupación.', 'Его опоздание сильно нас обеспокоило.'],
    ['orgullo', 'гордость', 'Sus padres sienten orgullo por sus resultados.', 'Его родители гордятся его результатами.'],
    ['ilusión', 'воодушевление', 'Preparamos el viaje con mucha ilusión.', 'Мы готовили поездку с большим воодушевлением.'],
    ['esperanza', 'надежда', 'Todavía tengo esperanza de encontrar mi maleta.', 'Я всё ещё надеюсь найти свой чемодан.'],
    ['decepción', 'разочарование', 'La cancelación del concierto fue una decepción.', 'Отмена концерта стала разочарованием.'],
    ['enfado', 'злость', 'Su enfado pasó después de hablar con calma.', 'Его злость прошла после спокойного разговора.'],
    ['nervios', 'волнение', 'Siempre tengo nervios antes de un examen.', 'Я всегда волнуюсь перед экзаменом.'],
    ['calma', 'спокойствие', 'Respira despacio y mantén la calma.', 'Дыши медленно и сохраняй спокойствие.'],
    ['confianza', 'уверенность', 'La práctica me dio confianza para hablar.', 'Практика придала мне уверенности в разговоре.'],
    ['curiosidad', 'любопытство', 'El niño miró el paquete con curiosidad.', 'Ребёнок с любопытством посмотрел на посылку.'],
    ['ansiedad', 'тревога', 'La espera le produce ansiedad.', 'Ожидание вызывает у него тревогу.'],
    ['culpa', 'вина', 'No fue tu culpa que perdiéramos el tren.', 'Ты не виноват в том, что мы опоздали на поезд.'],
    ['alivio', 'облегчение', 'Sentí alivio cuando encontré el pasaporte.', 'Я почувствовал облегчение, когда нашёл паспорт.'],
    ['cansancio', 'усталость', 'Después del viaje noté mucho cansancio.', 'После поездки я почувствовал сильную усталость.'],
    ['aburrimiento', 'скука', 'El aburrimiento desapareció cuando empezó la música.', 'Скука исчезла, когда заиграла музыка.'],
    ['emocionado', 'взволнованный', 'Estoy emocionado por mi primer viaje a México.', 'Я взволнован своей первой поездкой в Мексику.'],
    ['decepcionado', 'разочарованный', 'Salió decepcionado del restaurante.', 'Он вышел из ресторана разочарованным.'],
    ['enfadado', 'сердитый', 'Estoy enfadado porque nadie me avisó.', 'Я сержусь, потому что меня никто не предупредил.'],
    ['preocupado', 'обеспокоенный', 'Pareces preocupado por el examen.', 'Кажется, ты обеспокоен экзаменом.'],
    ['orgulloso', 'гордый', 'Estoy orgulloso de poder hablar español.', 'Я горжусь тем, что могу говорить по-испански.'],
    ['satisfecho', 'довольный', 'El cliente quedó satisfecho con el servicio.', 'Клиент остался доволен обслуживанием.'],
    ['confundido', 'растерянный', 'Estoy confundido porque las instrucciones no son claras.', 'Я растерян, потому что инструкции непонятны.'],
    ['sorprendido', 'удивлённый', 'Me quedé sorprendido al ver el resultado.', 'Я удивился, увидев результат.'],
    ['relajado', 'расслабленный', 'Después de caminar por la playa me siento relajado.', 'После прогулки по пляжу я чувствую себя расслабленным.'],
    ['incómodo', 'неловкий', 'Me siento incómodo hablando de dinero.', 'Мне неловко говорить о деньгах.'],
    ['parecer', 'казаться', 'Esta opción me parece más práctica.', 'Этот вариант кажется мне более практичным.'],
    ['opinar', 'считать', 'No todos pueden opinar lo mismo sobre la película.', 'Не все могут иметь одинаковое мнение о фильме.'],
    ['creer', 'полагать', 'Creo que mañana hará buen tiempo.', 'Я полагаю, что завтра будет хорошая погода.'],
    ['dudar', 'сомневаться', 'Empiezo a dudar de esa información.', 'Я начинаю сомневаться в этой информации.'],
    ['estar de acuerdo', 'быть согласным', 'No estoy de acuerdo con esa decisión.', 'Я не согласен с этим решением.'],
    ['tener razón', 'быть правым', 'Creo que tienes razón sobre el horario.', 'Я думаю, ты прав насчёт расписания.'],
    ['depender de', 'зависеть от', 'El precio puede depender de la temporada.', 'Цена может зависеть от сезона.'],
    ['preferencia', 'предпочтение', 'Mi preferencia es viajar en tren.', 'Я предпочитаю путешествовать на поезде.'],
    ['punto de vista', 'точка зрения', 'Entiendo tu punto de vista, aunque pienso diferente.', 'Я понимаю твою точку зрения, хотя думаю иначе.'],
    ['en mi opinión', 'по моему мнению', 'En mi opinión, el libro es mejor que la película.', 'По моему мнению, книга лучше фильма.'],
  ]),
  topic('Праздники и встречи', '🎉', [
    ['celebración', 'празднование', 'La celebración será en casa de mis padres.', 'Празднование будет в доме моих родителей.'],
    ['invitación', 'приглашение', 'Gracias por la invitación a tu cumpleaños.', 'Спасибо за приглашение на твой день рождения.'],
    ['cumpleaños', 'день рождения', 'Este sábado celebramos el cumpleaños de Clara.', 'В эту субботу мы отмечаем день рождения Клары.'],
    ['boda', 'свадьба', 'La boda empieza a las cinco de la tarde.', 'Свадьба начинается в пять часов вечера.'],
    ['aniversario', 'годовщина', 'Mis abuelos celebran su aniversario en junio.', 'Мои бабушка и дедушка отмечают годовщину в июне.'],
    ['regalo', 'подарок', 'He comprado un regalo para mi hermana.', 'Я купил подарок для сестры.'],
    ['sorpresa', 'сюрприз', 'Estamos preparando una sorpresa para Luis.', 'Мы готовим сюрприз для Луиса.'],
    ['tarta', 'торт', 'La tarta de chocolate está en la nevera.', 'Шоколадный торт находится в холодильнике.'],
    ['vela', 'свеча', 'El niño apagó cada vela de un soplido.', 'Ребёнок задул каждую свечу одним выдохом.'],
    ['brindis', 'тост', 'El padre de la novia hizo un brindis muy bonito.', 'Отец невесты произнёс очень красивый тост.'],
    ['invitado', 'гость', 'Cada invitado recibió una pequeña tarjeta.', 'Каждый гость получил небольшую открытку.'],
    ['anfitrión', 'хозяин встречи', 'El anfitrión recibió a todos en la puerta.', 'Хозяин встречи встретил всех у двери.'],
    ['celebrar', 'праздновать', 'Vamos a celebrar el final del curso juntos.', 'Мы собираемся вместе отпраздновать окончание курса.'],
    ['invitar', 'приглашать', 'Quiero invitar a Marta a cenar.', 'Я хочу пригласить Марту на ужин.'],
    ['aceptar', 'принимать', 'Me gustaría aceptar tu invitación.', 'Я хотел бы принять твоё приглашение.'],
    ['rechazar', 'отклонять', 'Tuvo que rechazar la invitación porque trabajaba.', 'Ему пришлось отклонить приглашение, потому что он работал.'],
    ['felicitar', 'поздравлять', 'Voy a llamar a Ana para felicitarla.', 'Я позвоню Ане, чтобы поздравить её.'],
    ['regalar', 'дарить', 'Mis amigos quieren regalarme un libro.', 'Мои друзья хотят подарить мне книгу.'],
    ['soplar', 'задувать', 'Todos empezaron a cantar antes de soplar las velas.', 'Все начали петь перед тем, как задуть свечи.'],
    ['despedirse', 'прощаться', 'Nos quedamos en la puerta para despedirnos.', 'Мы остались у двери, чтобы попрощаться.'],
    ['quedar con', 'встречаться с', 'Esta tarde voy a quedar con unos amigos.', 'Сегодня днём я встречаюсь с друзьями.'],
    ['venir bien', 'быть удобным', '¿Te viene bien el domingo por la tarde?', 'Тебе удобно в воскресенье днём?'],
    ['¿Te apetece…?', 'Хочешь…?', '¿Te apetece tomar algo después del trabajo?', 'Хочешь что-нибудь выпить после работы?'],
    ['Me encantaría', 'С удовольствием', 'Me encantaría ir al concierto contigo.', 'Я бы с удовольствием пошёл с тобой на концерт.'],
    ['Lo siento, no puedo', 'К сожалению, я не могу', 'Lo siento, no puedo ir a la cena del viernes.', 'К сожалению, я не могу пойти на ужин в пятницу.'],
    ['pasarlo bien', 'хорошо проводить время', 'Espero que todos puedan pasarlo bien en la fiesta.', 'Надеюсь, все смогут хорошо провести время на вечеринке.'],
  ]),
  topic('Быт и район', '🧹', [
    ['vecindario', 'окрестности', 'Nuestro vecindario es tranquilo y tiene muchos árboles.', 'Наши окрестности тихие, и там много деревьев.'],
    ['comunidad', 'сообщество жильцов', 'La comunidad ha decidido reparar el ascensor.', 'Сообщество жильцов решило отремонтировать лифт.'],
    ['propietario', 'владелец жилья', 'El propietario vive en el piso de arriba.', 'Владелец жилья живёт этажом выше.'],
    ['inquilino', 'арендатор', 'El nuevo inquilino se mudó ayer.', 'Новый арендатор переехал вчера.'],
    ['mudanza', 'переезд', 'La mudanza duró todo el fin de semana.', 'Переезд занял все выходные.'],
    ['factura', 'счёт на оплату', 'La factura de la luz llegó por correo electrónico.', 'Счёт за электричество пришёл по электронной почте.'],
    ['avería', 'поломка', 'Hay una avería en la calefacción.', 'В отоплении произошла поломка.'],
    ['portal', 'подъезд', 'Te espero en el portal a las ocho.', 'Я жду тебя в подъезде в восемь.'],
    ['rellano', 'лестничная площадка', 'La bicicleta no puede quedarse en el rellano.', 'Велосипед нельзя оставлять на лестничной площадке.'],
    ['contenedor', 'мусорный контейнер', 'El contenedor de papel está junto al supermercado.', 'Контейнер для бумаги находится рядом с супермаркетом.'],
    ['basura', 'мусор', '¿Puedes sacar la basura antes de salir?', 'Можешь вынести мусор перед выходом?'],
    ['reciclaje', 'переработка отходов', 'En este edificio hay un espacio para el reciclaje.', 'В этом здании есть место для переработки отходов.'],
    ['tendedero', 'сушилка для белья', 'La ropa está seca en el tendedero.', 'Одежда высохла на сушилке.'],
    ['aspiradora', 'пылесос', 'La aspiradora está guardada detrás de la puerta.', 'Пылесос хранится за дверью.'],
    ['escoba', 'метла', 'Necesito una escoba para limpiar el balcón.', 'Мне нужна метла, чтобы убрать балкон.'],
    ['fregar', 'мыть посуду', 'Me toca fregar después de la cena.', 'После ужина моя очередь мыть посуду.'],
    ['barrer', 'подметать', 'Voy a barrer la cocina antes de cocinar.', 'Я подмету кухню перед приготовлением еды.'],
    ['planchar', 'гладить', 'No me gusta planchar las camisas.', 'Я не люблю гладить рубашки.'],
    ['tender', 'развешивать бельё', 'Voy a tender la ropa en la terraza.', 'Я собираюсь развесить бельё на террасе.'],
    ['recoger la casa', 'прибираться дома', 'Tenemos que recoger la casa antes de que lleguen los invitados.', 'Нам нужно прибраться дома до прихода гостей.'],
    ['arreglar', 'чинить', 'El técnico viene mañana para arreglar la lavadora.', 'Мастер придёт завтра, чтобы починить стиральную машину.'],
    ['romperse', 'ломаться', 'La calefacción suele romperse en invierno.', 'Отопление обычно ломается зимой.'],
    ['funcionar', 'работать исправно', 'El ascensor vuelve a funcionar con normalidad.', 'Лифт снова работает нормально.'],
    ['molestar', 'мешать', 'Perdona si la música puede molestar a los vecinos.', 'Извини, если музыка может помешать соседям.'],
    ['hacer ruido', 'шуметь', 'No se puede hacer ruido después de las once.', 'После одиннадцати нельзя шуметь.'],
    ['pedir prestado', 'брать взаймы', 'Voy a pedir prestado un taladro al vecino.', 'Я попрошу у соседа дрель взаймы.'],
    ['devolver', 'возвращать', 'No olvides devolver las llaves al propietario.', 'Не забудь вернуть ключи владельцу жилья.'],
    ['quedarse sin luz', 'остаться без электричества', 'Durante la tormenta podemos quedarnos sin luz.', 'Во время грозы мы можем остаться без электричества.'],
  ]),
  topic('Проблемы и экстренные ситуации', '🆘', [
    ['urgencia', 'неотложная ситуация', 'El hospital tiene una entrada especial para cada urgencia.', 'В больнице есть отдельный вход для неотложных случаев.'],
    ['accidente', 'авария', 'Hubo un accidente cerca de la estación.', 'Рядом со станцией произошла авария.'],
    ['peligro', 'опасность', 'La señal avisa del peligro en la carretera.', 'Знак предупреждает об опасности на дороге.'],
    ['robo', 'кража', 'Denuncié el robo del móvil en la comisaría.', 'Я сообщил о краже телефона в полицейском участке.'],
    ['ladrón', 'вор', 'Un testigo vio al ladrón salir de la tienda.', 'Свидетель видел, как вор вышел из магазина.'],
    ['denuncia', 'заявление в полицию', 'La policía tomó nota de la denuncia.', 'Полиция зарегистрировала заявление.'],
    ['testigo', 'свидетель', 'El testigo explicó lo que había visto.', 'Свидетель объяснил, что он видел.'],
    ['bombero', 'пожарный', 'El bombero pidió a todos que salieran del edificio.', 'Пожарный попросил всех выйти из здания.'],
    ['incendio', 'пожар', 'El incendio empezó en una cocina vacía.', 'Пожар начался на пустой кухне.'],
    ['humo', 'дым', 'Vimos humo salir de una ventana.', 'Мы увидели дым, выходивший из окна.'],
    ['seguro de viaje', 'туристическая страховка', 'Mi seguro de viaje cubre la atención médica.', 'Моя туристическая страховка покрывает медицинскую помощь.'],
    ['pérdida', 'потеря', 'La pérdida del pasaporte complicó el viaje.', 'Потеря паспорта осложнила поездку.'],
    ['daño', 'ущерб', 'La tormenta causó daño en varias casas.', 'Гроза нанесла ущерб нескольким домам.'],
    ['averiado', 'неисправный', 'El coche está averiado y no puede arrancar.', 'Машина неисправна и не заводится.'],
    ['desaparecido', 'пропавший', 'La policía busca a un excursionista desaparecido.', 'Полиция ищет пропавшего туриста.'],
    ['pedir ayuda', 'просить помощи', 'No dudes en pedir ayuda si te pierdes.', 'Не стесняйся просить помощи, если заблудишься.'],
    ['avisar', 'предупреждать', 'Debes avisar a recepción si encuentras un problema.', 'Ты должен предупредить администратора, если обнаружишь проблему.'],
    ['denunciar', 'заявлять в полицию', 'Fui a denunciar la pérdida de mis documentos.', 'Я пошёл заявить в полицию о потере документов.'],
    ['rescatar', 'спасать', 'Los bomberos lograron rescatar al perro.', 'Пожарным удалось спасти собаку.'],
    ['proteger', 'защищать', 'Esta crema sirve para proteger la piel del sol.', 'Этот крем служит для защиты кожи от солнца.'],
    ['evitar', 'избегать', 'Es mejor evitar esa carretera cuando nieva.', 'Лучше избегать этой дороги во время снегопада.'],
    ['tener cuidado', 'быть осторожным', 'Hay que tener cuidado al cruzar esta avenida.', 'Нужно быть осторожным, переходя этот проспект.'],
    ['estar perdido', 'заблудиться', 'Creo que estoy perdido; no reconozco esta calle.', 'Кажется, я заблудился: я не узнаю эту улицу.'],
    ['quedarse encerrado', 'оказаться запертым', 'El niño llegó a quedarse encerrado en el ascensor.', 'Ребёнок оказался заперт в лифте.'],
    ['llamar a emergencias', 'звонить в экстренную службу', 'Debes llamar a emergencias si alguien no puede respirar.', 'Нужно звонить в экстренную службу, если человек не может дышать.'],
    ['¿Qué ha pasado?', 'Что произошло?', '¿Qué ha pasado delante del banco?', 'Что произошло перед банком?'],
    ['Necesito ayuda', 'Мне нужна помощь', 'Necesito ayuda para encontrar a mi hija.', 'Мне нужна помощь, чтобы найти мою дочь.'],
    ['No funciona', 'Не работает', 'No funciona la tarjeta de la habitación.', 'Карта от номера не работает.'],
    ['salida de emergencia', 'аварийный выход', 'La salida de emergencia está al final del pasillo.', 'Аварийный выход находится в конце коридора.'],
    ['extintor', 'огнетушитель', 'Hay un extintor junto a la puerta.', 'Рядом с дверью находится огнетушитель.'],
    ['alarma', 'сигнализация', 'La alarma empezó a sonar durante la noche.', 'Ночью сработала сигнализация.'],
    ['llamar al 112', 'звонить по номеру 112', 'Si hay un incendio, debes llamar al 112.', 'Если начался пожар, нужно позвонить по номеру 112.'],
    ['perder los documentos', 'потерять документы', 'Fui a la comisaría después de perder los documentos.', 'После потери документов я пошёл в полицейский участок.'],
    ['cancelar la tarjeta', 'заблокировать банковскую карту', 'Llama al banco para cancelar la tarjeta robada.', 'Позвони в банк, чтобы заблокировать украденную карту.'],
    ['pedir un médico', 'вызвать врача', 'El huésped se encuentra mal y quiere pedir un médico.', 'Постояльцу плохо, и он хочет вызвать врача.'],
    ['tener una avería', 'сломаться', 'El coche tuvo una avería en la carretera.', 'Машина сломалась на дороге.'],
    ['estar herido', 'быть раненым', 'El ciclista está herido, pero puede hablar.', 'Велосипедист ранен, но может говорить.'],
    ['estar a salvo', 'быть в безопасности', 'Todos salieron del edificio y están a salvo.', 'Все вышли из здания и находятся в безопасности.'],
    ['corte', 'порез', 'Tengo un corte pequeño en el dedo.', 'У меня небольшой порез на пальце.'],
    ['quemadura', 'ожог', 'Enfría la quemadura con agua corriente.', 'Охлади ожог проточной водой.'],
    ['caída', 'падение', 'Después de la caída le dolía la espalda.', 'После падения у него болела спина.'],
    ['choque', 'столкновение', 'Hubo un choque entre dos coches en la avenida.', 'На проспекте столкнулись две машины.'],
    ['evacuación', 'эвакуация', 'La evacuación del hotel duró pocos minutos.', 'Эвакуация из отеля заняла несколько минут.'],
    ['primeros auxilios', 'первая помощь', 'El guía sabe prestar primeros auxilios.', 'Гид умеет оказывать первую помощь.'],
    ['zona segura', 'безопасная зона', 'Espere en la zona segura hasta nuevo aviso.', 'Ждите в безопасной зоне до дальнейших указаний.'],
    ['número de emergencia', 'номер экстренной службы', 'Guarda el número de emergencia en el teléfono.', 'Сохрани номер экстренной службы в телефоне.'],
    ['objeto perdido', 'потерянная вещь', 'Entregué el objeto perdido en recepción.', 'Я отдал потерянную вещь администратору.'],
    ['mantener la calma', 'сохранять спокойствие', 'Intenta mantener la calma y explica qué ha pasado.', 'Постарайся сохранять спокойствие и объясни, что произошло.'],
  ]),
  topic('Техника и устройства', '💻', [
    ['pantalla', 'экран', 'La pantalla del móvil está rota.', 'Экран телефона разбит.'],
    ['teclado', 'клавиатура', 'Este teclado tiene letras españolas.', 'На этой клавиатуре есть испанские буквы.'],
    ['ratón', 'компьютерная мышь', 'El ratón no responde cuando hago clic.', 'Компьютерная мышь не реагирует на щелчок.'],
    ['altavoz', 'динамик', 'El sonido sale por el altavoz izquierdo.', 'Звук идёт из левого динамика.'],
    ['auriculares', 'наушники', 'Uso auriculares para escuchar el ejercicio.', 'Я использую наушники, чтобы слушать упражнение.'],
    ['cable', 'кабель', 'Necesito un cable más largo para cargar el móvil.', 'Мне нужен более длинный кабель для зарядки телефона.'],
    ['enchufe', 'розетка', 'Hay un enchufe junto a la cama.', 'Рядом с кроватью есть розетка.'],
    ['archivo', 'файл', 'He guardado el archivo en una carpeta nueva.', 'Я сохранил файл в новой папке.'],
    ['carpeta', 'папка', 'Las fotos están en la carpeta de vacaciones.', 'Фотографии находятся в папке с отпуском.'],
    ['aplicación', 'приложение', 'Esta aplicación funciona sin conexión.', 'Это приложение работает без подключения к интернету.'],
    ['cuenta de usuario', 'учётная запись', 'Puedes recuperar tu cuenta de usuario por correo.', 'Ты можешь восстановить свою учётную запись по электронной почте.'],
    ['código', 'код', 'Introduce el código que recibiste por mensaje.', 'Введи код, который пришёл тебе в сообщении.'],
    ['copia de seguridad', 'резервная копия', 'Hago una copia de seguridad cada semana.', 'Я создаю резервную копию каждую неделю.'],
    ['actualización', 'обновление', 'La última actualización mejora la velocidad.', 'Последнее обновление повышает скорость работы.'],
    ['conexión', 'соединение', 'La conexión a internet es inestable hoy.', 'Сегодня интернет-соединение нестабильно.'],
    ['cobertura', 'сигнал сети', 'En las montañas hay poca cobertura.', 'В горах слабый сигнал сети.'],
    ['descargar', 'скачивать', 'Puedes descargar el mapa antes del viaje.', 'Ты можешь скачать карту перед поездкой.'],
    ['subir un archivo', 'загружать файл', 'Voy a subir un archivo a la carpeta compartida.', 'Я загружу файл в общую папку.'],
    ['guardar', 'сохранять', 'No olvides guardar los cambios antes de salir.', 'Не забудь сохранить изменения перед выходом.'],
    ['adjuntar', 'прикреплять', 'Voy a adjuntar el documento al correo.', 'Я прикреплю документ к письму.'],
    ['instalar', 'устанавливать', 'Necesito instalar la aplicación en el teléfono.', 'Мне нужно установить приложение на телефон.'],
    ['actualizar', 'обновлять', 'Conviene actualizar el sistema esta noche.', 'Стоит обновить систему сегодня ночью.'],
    ['reiniciar', 'перезапускать', 'Prueba a reiniciar el ordenador.', 'Попробуй перезапустить компьютер.'],
    ['encender', 'включать', 'Pulsa este botón para encender la pantalla.', 'Нажми эту кнопку, чтобы включить экран.'],
    ['apagar', 'выключать', 'Recuerda apagar el ordenador al terminar.', 'Не забудь выключить компьютер после завершения работы.'],
    ['conectarse', 'подключаться', 'No puedo conectarme a la red del hotel.', 'Я не могу подключиться к сети отеля.'],
    ['compartir', 'делиться', 'Puedes compartir la ubicación con tu familia.', 'Ты можешь поделиться местоположением с семьёй.'],
    ['hacer clic', 'нажимать', 'Debes hacer clic en el enlace de confirmación.', 'Нужно нажать на ссылку подтверждения.'],
    ['estar sin batería', 'быть с разряженной батареей', 'No puedo llamar porque el móvil está sin batería.', 'Я не могу позвонить, потому что телефон разряжен.'],
    ['modo avión', 'авиарежим', 'Activa el modo avión antes del despegue.', 'Включи авиарежим перед взлётом.'],
  ]),
  topic('Культура и медиа', '🎭', [
    ['película', 'фильм', 'La película cuenta la historia de una familia.', 'Фильм рассказывает историю одной семьи.'],
    ['serie', 'сериал', 'Esta serie tiene ocho capítulos cortos.', 'В этом сериале восемь коротких серий.'],
    ['documental', 'документальный фильм', 'Vimos un documental sobre la naturaleza de Chile.', 'Мы посмотрели документальный фильм о природе Чили.'],
    ['novela', 'роман', 'La novela está ambientada en Barcelona.', 'Действие романа происходит в Барселоне.'],
    ['cuento', 'рассказ', 'El profesor leyó un cuento en voz alta.', 'Преподаватель прочитал рассказ вслух.'],
    ['poema', 'стихотворение', 'Aprendimos un poema breve de memoria.', 'Мы выучили короткое стихотворение наизусть.'],
    ['noticia', 'новость', 'He leído una noticia importante esta mañana.', 'Сегодня утром я прочитал важную новость.'],
    ['programa', 'передача', 'Mi abuela escucha este programa de radio cada día.', 'Моя бабушка каждый день слушает эту радиопередачу.'],
    ['capítulo', 'серия', 'El último capítulo termina con una sorpresa.', 'Последняя серия заканчивается сюрпризом.'],
    ['personaje', 'персонаж', 'Mi personaje favorito es la hermana mayor.', 'Мой любимый персонаж — старшая сестра.'],
    ['actor', 'актёр', 'El actor aprendió español para la película.', 'Актёр выучил испанский язык для фильма.'],
    ['actriz', 'актриса', 'La actriz recibió un premio por su trabajo.', 'Актриса получила награду за свою работу.'],
    ['director', 'режиссёр', 'El director presentó la película en el festival.', 'Режиссёр представил фильм на фестивале.'],
    ['autor', 'автор', 'El autor firmó libros después de la charla.', 'Автор подписывал книги после встречи.'],
    ['exposición', 'выставка', 'La exposición abre hasta las nueve los viernes.', 'По пятницам выставка открыта до девяти.'],
    ['obra de teatro', 'спектакль', 'La obra de teatro dura una hora y media.', 'Спектакль длится полтора часа.'],
    ['festival', 'фестиваль', 'El festival reúne música y cine latinoamericano.', 'Фестиваль объединяет латиноамериканскую музыку и кино.'],
    ['estreno', 'премьера', 'Las entradas para el estreno ya están agotadas.', 'Билеты на премьеру уже распроданы.'],
    ['premio', 'награда', 'La película ganó un premio internacional.', 'Фильм получил международную награду.'],
    ['reseña', 'рецензия', 'Escribí una reseña breve después de leer el libro.', 'После прочтения книги я написал короткую рецензию.'],
    ['argumento', 'сюжет', 'El argumento parece sencillo al principio.', 'Сначала сюжет кажется простым.'],
    ['escena', 'сцена фильма', 'Esa escena ocurre en una estación vacía.', 'Эта сцена происходит на пустой станции.'],
    ['subtítulos', 'субтитры', 'Veo la serie con subtítulos en español.', 'Я смотрю сериал с испанскими субтитрами.'],
    ['doblado', 'дублированный', 'Prefiero ver el documental doblado al español.', 'Я предпочитаю смотреть документальный фильм с испанским дубляжом.'],
    ['tratar de', 'быть посвящённым', 'La novela parece tratar de una amistad imposible.', 'Кажется, роман посвящён невозможной дружбе.'],
    ['recomendar', 'рекомендовать', '¿Puedes recomendar una película para esta noche?', 'Можешь порекомендовать фильм на сегодняшний вечер?'],
    ['publicar', 'публиковать', 'La revista va a publicar la entrevista mañana.', 'Журнал опубликует интервью завтра.'],
    ['entrevistar', 'брать интервью', 'Una periodista vino a entrevistar al cantante.', 'Журналистка пришла взять интервью у певца.'],
    ['emocionante', 'захватывающий', 'El final es emocionante y bastante inesperado.', 'Финал захватывающий и довольно неожиданный.'],
    ['entretenido', 'увлекательный', 'Es un libro ligero y entretenido.', 'Это лёгкая и увлекательная книга.'],
  ]),
  topic('Связующие слова и полезные конструкции', '🔗', [
    ['entonces', 'тогда', 'No había autobuses, entonces pedimos un taxi.', 'Автобусов не было, поэтому мы вызвали такси.'],
    ['además', 'кроме того', 'El piso es luminoso y además está cerca del metro.', 'Квартира светлая и, кроме того, находится рядом с метро.'],
    ['aunque', 'хотя', 'Salimos a caminar aunque hacía frío.', 'Мы пошли гулять, хотя было холодно.'],
    ['por eso', 'поэтому', 'Mañana trabajo temprano; por eso me voy a casa.', 'Завтра я рано работаю, поэтому иду домой.'],
    ['sin embargo', 'однако', 'La tarea era difícil; sin embargo, todos la terminaron.', 'Задание было трудным, однако все его закончили.'],
    ['mientras', 'пока', 'Escucho música mientras preparo la cena.', 'Я слушаю музыку, пока готовлю ужин.'],
    ['cuando', 'когда', 'Llámame cuando llegues al hotel.', 'Позвони мне, когда приедешь в отель.'],
    ['al final', 'в итоге', 'Al final encontramos una mesa libre.', 'В итоге мы нашли свободный столик.'],
    ['de repente', 'внезапно', 'De repente empezó a llover con fuerza.', 'Внезапно начался сильный дождь.'],
    ['por ejemplo', 'например', 'Podemos visitar otra ciudad, por ejemplo, Toledo.', 'Мы можем посетить другой город, например Толедо.'],
    ['en general', 'в целом', 'En general, el transporte público funciona bien.', 'В целом общественный транспорт работает хорошо.'],
    ['todavía', 'всё ещё', 'Todavía no he recibido la confirmación.', 'Я всё ещё не получил подтверждение.'],
    ['ya', 'уже', 'Ya hemos reservado la habitación.', 'Мы уже забронировали номер.'],
    ['alguna vez', 'когда-нибудь', '¿Has estado alguna vez en México?', 'Ты когда-нибудь был в Мексике?'],
    ['cada vez', 'с каждым разом', 'Cada vez entiendo mejor las canciones.', 'С каждым разом я лучше понимаю песни.'],
    ['en cambio', 'зато', 'Yo prefiero el campo; mi hermano, en cambio, vive en la ciudad.', 'Я предпочитаю сельскую местность, а мой брат, напротив, живёт в городе.'],
    ['por un lado', 'с одной стороны', 'Por un lado, el hotel es barato y está bien situado.', 'С одной стороны, отель недорогой и хорошо расположен.'],
    ['por otro lado', 'с другой стороны', 'Por otro lado, la habitación es bastante pequeña.', 'С другой стороны, номер довольно маленький.'],
    ['primero que nada', 'прежде всего', 'Primero que nada, comprueba la fecha del billete.', 'Прежде всего проверь дату на билете.'],
    ['tener que', 'быть должным', 'Tengo que terminar el informe esta tarde.', 'Мне нужно закончить отчёт сегодня днём.'],
    ['hay que', 'нужно', 'Hay que validar el billete antes de subir.', 'Нужно прокомпостировать билет перед посадкой.'],
    ['ir a', 'собираться', 'Voy a llamar al médico después del desayuno.', 'Я собираюсь позвонить врачу после завтрака.'],
    ['acabar de', 'только что сделать', 'Acabo de recibir tu mensaje.', 'Я только что получил твоё сообщение.'],
    ['estar a punto de', 'вот-вот сделать', 'El tren está a punto de salir.', 'Поезд вот-вот отправится.'],
    ['seguir haciendo', 'продолжать делать', 'Quiero seguir haciendo ejercicios cada día.', 'Я хочу продолжать выполнять упражнения каждый день.'],
    ['dejar de', 'переставать', 'Intento dejar de mirar el móvil por la noche.', 'Я стараюсь перестать смотреть в телефон по вечерам.'],
    ['volver a', 'снова делать', 'Tuve que volver a escribir la dirección.', 'Мне пришлось снова написать адрес.'],
    ['soler', 'обычно делать', 'Suelo desayunar antes de las ocho.', 'Обычно я завтракаю до восьми.'],
    ['me parece que', 'мне кажется', 'Me parece que esta respuesta es correcta.', 'Мне кажется, этот ответ правильный.'],
    ['no pasa nada', 'ничего страшного', 'No pasa nada si llegas cinco minutos tarde.', 'Ничего страшного, если ты опоздаешь на пять минут.'],
    ['depende de', 'зависит от', 'El precio depende de la temporada.', 'Цена зависит от сезона.'],
    ['a lo mejor', 'возможно', 'A lo mejor podemos cenar juntos mañana.', 'Возможно, завтра мы сможем поужинать вместе.'],
    ['claro que sí', 'конечно', '— ¿Puedes ayudarme? — Claro que sí.', '— Можешь мне помочь? — Конечно.'],
    ['es decir', 'то есть', 'La tienda cierra a mediodía, es decir, a las doce.', 'Магазин закрывается в полдень, то есть в двенадцать.'],
  ]),
];
