import type { A2VocabularyTopic } from './a2-vocabulary.ts';

export const deleA2TopicName = 'DELE A2 · Повседневные ситуации';
export const deleA2Sources = {
  curriculum: 'https://cvc.cervantes.es/ensenanza/biblioteca_ele/plan_curricular/niveles/09_nociones_especificas_inventario_a1-a2.htm',
  model: 'https://examenes.cervantes.es/sites/default/files/DELE-A2_v2020_Modelo0.pdf',
};

// Original learning examples for the everyday domains in the Cervantes A1–A2
// inventory and DELE A2 model. These are not quotations or official exam tasks.
const rows: [es: string, ru: string, example: string, exampleRu: string][] = [
  ['apellidarse', 'носить фамилию', 'Mi hijo va a apellidarse García, como yo.', 'Мой сын будет носить фамилию Гарсия, как и я.'],
  ['prefijo', 'телефонный код', 'El prefijo de España es el 34.', 'Телефонный код Испании — 34.'],
  ['maletín', 'портфель', 'Llevo los documentos en un maletín negro.', 'Я ношу документы в чёрном портфеле.'],
  ['socio', 'партнёр по бизнесу', 'Mi socio trabaja conmigo en la tienda.', 'Мой партнёр по бизнесу работает со мной в магазине.'],
  ['infusión', 'травяной чай', 'Por la noche tomo una infusión sin azúcar.', 'Вечером я пью травяной чай без сахара.'],
  ['merluza', 'хек', 'Hoy tenemos merluza con patatas en el menú.', 'Сегодня у нас в меню хек с картофелем.'],
  ['sardina', 'сардина', 'Quiero probar una sardina a la plancha.', 'Я хочу попробовать сардину на гриле.'],
  ['perejil', 'петрушка', 'Añade un poco de perejil a la sopa.', 'Добавь в суп немного петрушки.'],
  ['ternera', 'телятина', '¿Cuánto cuesta un kilo de ternera?', 'Сколько стоит килограмм телятины?'],
  ['cordero', 'баранина', 'Mi padre prepara cordero para la cena del domingo.', 'Мой отец готовит баранину на воскресный ужин.'],
  ['plato combinado', 'комплексное блюдо', 'El plato combinado lleva pollo, arroz y ensalada.', 'В комплексное блюдо входят курица, рис и салат.'],
  ['pizzería', 'пиццерия', 'La pizzería de mi barrio abre a las siete.', 'Пиццерия в моём районе открывается в семь.'],
  ['academia', 'учебный центр', 'Estudio español en una academia cerca de casa.', 'Я учу испанский в учебном центре недалеко от дома.'],
  ['aula', 'учебная аудитория', 'El aula de español está en la segunda planta.', 'Аудитория для занятий испанским находится на втором этаже.'],
  ['fotocopiadora', 'копировальный аппарат', 'La fotocopiadora está al lado de la impresora.', 'Копировальный аппарат находится рядом с принтером.'],
  ['comercial', 'торговый представитель', 'El comercial visita a los clientes por la mañana.', 'Торговый представитель посещает клиентов по утрам.'],
  ['empresario', 'предприниматель', 'El empresario tiene una pequeña tienda de ropa.', 'У предпринимателя небольшой магазин одежды.'],
  ['multinacional', 'международная компания', 'Mi hermana trabaja en una multinacional con oficinas en Madrid.', 'Моя сестра работает в международной компании с офисами в Мадриде.'],
  ["frutería", "фруктовая лавка", "En la frutería compro manzanas y plátanos.", "В фруктовой лавке я покупаю яблоки и бананы."],
  ['quiosco', 'киоск', 'Compro el periódico en el quiosco de la esquina.', 'Я покупаю газету в киоске на углу.'],
  ['presentador', 'ведущий', 'El presentador habla con una cantante en el programa.', 'Ведущий беседует с певицей в передаче.'],
  ['cabina', 'телефонная будка', 'Hay una cabina telefónica junto a la estación.', 'Рядом со станцией есть телефонная будка.'],
  ['postal', 'почтовая открытка', 'Te envío una postal desde Valencia.', 'Я отправляю тебе открытку из Валенсии.'],
  ['parchís', 'парчис', 'Los domingos jugamos al parchís con los abuelos.', 'По воскресеньям мы играем в парчис с бабушкой и дедушкой.'],
  ['zoológico', 'зоопарк', 'El zoológico abre todos los días a las diez.', 'Зоопарк открывается каждый день в десять.'],
  ['musical', 'мюзикл', 'Tenemos entradas para un musical el viernes.', 'У нас есть билеты на мюзикл в пятницу.'],
  ['ópera', 'опера', 'Mi abuela quiere ir a la ópera por su cumpleaños.', 'Моя бабушка хочет сходить в оперу на свой день рождения.'],
  ['gimnasia', 'гимнастика', 'Hago gimnasia en casa antes de desayunar.', 'Я занимаюсь гимнастикой дома перед завтраком.'],
  ['tarjeta de visita', 'визитная карточка', 'En mi tarjeta de visita aparece mi teléfono.', 'На моей визитной карточке указан мой телефон.'],
  ['tarjeta de estudiante', 'студенческая карточка', 'Con la tarjeta de estudiante la entrada cuesta menos.', 'Со студенческой карточкой вход стоит дешевле.'],
  ['biblioteca municipal', 'городская библиотека', 'La biblioteca municipal presta libros durante dos semanas.', 'Городская библиотека выдаёт книги на две недели.'],
  ['compañero de clase', 'одноклассник', 'Mi compañero de clase me ayuda con los deberes.', 'Мой одноклассник помогает мне с домашним заданием.'],
  ['hacer un curso', 'проходить курс', 'Quiero hacer un curso de cocina en verano.', 'Я хочу пройти курс кулинарии летом.'],
  ['pagar la matrícula', 'оплачивать запись на обучение', 'Puedes pagar la matrícula en la secretaría de la escuela.', 'Ты можешь оплатить запись на обучение в секретариате школы.'],
  ['dar clases', 'преподавать', 'Voy a dar clases de música los martes.', 'Я буду преподавать музыку по вторникам.'],
  ['cometer un error', 'допускать ошибку', 'Es normal cometer un error cuando aprendes una lengua.', 'Допускать ошибку, когда учишь язык, — нормально.'],
  ['hacer una redacción', 'писать сочинение', 'Tenemos que hacer una redacción sobre nuestras vacaciones.', 'Нам нужно написать сочинение о наших каникулах.'],
  ['aprender una regla', 'выучивать правило', 'Para este ejercicio necesitas aprender una regla nueva.', 'Для этого упражнения тебе нужно выучить новое правило.'],
  ['hacer fotocopias', 'делать ксерокопии', 'Necesito hacer fotocopias de estos documentos.', 'Мне нужно сделать ксерокопии этих документов.'],
  ['preparar una factura', 'составлять счёт на оплату', 'Tengo que preparar una factura para el cliente.', 'Мне нужно составить счёт на оплату для клиента.'],
  ['contestar al teléfono', 'отвечать на телефонный звонок', '¿Puedes contestar al teléfono mientras atiendo al cliente?', 'Можешь ответить на телефонный звонок, пока я обслуживаю клиента?'],
  ['estar en paro', 'быть безработным', 'Después de estar en paro, Luis encontró trabajo en una tienda.', 'После периода безработицы Луис нашёл работу в магазине.'],
  ['estar jubilado', 'быть на пенсии', 'A mi abuelo le gusta estar jubilado.', 'Моему дедушке нравится быть на пенсии.'],
  ['ganar dinero', 'зарабатывать деньги', 'En verano quiero trabajar para ganar dinero.', 'Летом я хочу работать, чтобы заработать деньги.'],
  ['enviar el currículum', 'отправлять резюме', 'Puedes enviar el currículum por correo electrónico.', 'Ты можешь отправить резюме по электронной почте.'],
  ['buscar trabajo', 'искать работу', 'Voy a buscar trabajo cerca de mi casa.', 'Я буду искать работу недалеко от дома.'],
  ["pescadería", "рыбная лавка", "La pescadería del mercado vende pescado fresco.", "Рыбная лавка на рынке продаёт свежую рыбу."],
  ['pedir la cuenta', 'просить счёт', 'Vamos a pedir la cuenta porque el restaurante va a cerrar.', 'Давай попросим счёт, потому что ресторан скоро закроется.'],
  ['plato del día', 'блюдо дня', 'El plato del día es pescado con verduras.', 'Блюдо дня — рыба с овощами.'],
  ["carnicería", "мясная лавка", "En la carnicería puedes comprar pollo y ternera.", "В мясной лавке ты можешь купить курицу и телятину."],
  ['sin gas', 'без газа', 'Quiero una botella de agua sin gas, por favor.', 'Я хочу бутылку воды без газа, пожалуйста.'],
  ['con hielo', 'со льдом', 'En verano me gusta tomar café con hielo.', 'Летом мне нравится пить кофе со льдом.'],
  ['a la plancha', 'на гриле', 'Prefiero el pollo a la plancha con ensalada.', 'Я предпочитаю курицу на гриле с салатом.'],
  ['de segunda mano', 'подержанный', 'Compré una bicicleta de segunda mano para ir al trabajo.', 'Я купил подержанный велосипед, чтобы ездить на работу.'],
  ["estanco", "табачная лавка", "Puedes comprar sellos en el estanco de la plaza.", "Ты можешь купить почтовые марки в табачной лавке на площади."],
  ["peine", "расчёска", "Siempre llevo un peine pequeño en el bolso.", "Я всегда ношу маленькую расчёску в сумке."],
  ['cambiar de talla', 'менять на другой размер', 'Quiero cambiar de talla porque estos pantalones son pequeños.', 'Я хочу обменять брюки на другой размер, потому что эти малы.'],
  ['devolver el dinero', 'возвращать деньги', 'La tienda va a devolver el dinero si traes el recibo.', 'Магазин вернёт деньги, если ты принесёшь чек.'],
  ["hijo único", "единственный ребёнок", "Mi primo es hijo único y vive con sus padres.", "Мой двоюродный брат — единственный ребёнок и живёт с родителями."],
  ['habitación individual', 'одноместный номер', 'Quiero una habitación individual para dos noches.', 'Я хочу одноместный номер на две ночи.'],
  ['habitación doble', 'двухместный номер', 'La habitación doble tiene dos camas y un baño.', 'В двухместном номере две кровати и ванная комната.'],
  ['pensión completa', 'полный пансион', 'La pensión completa incluye desayuno, comida y cena.', 'Полный пансион включает завтрак, обед и ужин.'],
  ['media pensión', 'полупансион', 'Elegimos media pensión porque vamos a comer fuera del hotel.', 'Мы выбрали полупансион, потому что будем обедать вне отеля.'],
  ['billete de ida', 'билет в одну сторону', 'Necesito un billete de ida a Salamanca.', 'Мне нужен билет в одну сторону до Саламанки.'],
  ["gemelos", "близнецы", "Mis hermanos son gemelos, pero tienen gustos diferentes.", "Мои братья — близнецы, но у них разные вкусы."],
  ['hacer transbordo', 'делать пересадку', 'Para llegar al museo tienes que hacer transbordo en la estación central.', 'Чтобы добраться до музея, тебе нужно сделать пересадку на центральной станции.'],
  ['ir andando', 'идти пешком', 'Prefiero ir andando porque la oficina está cerca.', 'Я предпочитаю идти пешком, потому что офис близко.'],
  ['compartir piso', 'совместно снимать квартиру', 'Quiero compartir piso con otros estudiantes.', 'Я хочу снимать квартиру вместе с другими студентами.'],
  ['gastos incluidos', 'расходы включены', 'La habitación cuesta cuatrocientos euros al mes, con gastos incluidos.', 'Комната стоит четыреста евро в месяц с включёнными расходами.'],
  ['amueblado', 'меблированный', 'Buscamos un piso amueblado con dos dormitorios.', 'Мы ищем меблированную квартиру с двумя спальнями.'],
  ["dejar una nota", "оставлять записку", "Voy a dejar una nota en la mesa para mi compañero de piso.", "Я оставлю записку на столе для соседа по квартире."],
  ['tender la ropa', 'развешивать бельё', 'Después de lavar, tengo que tender la ropa en el balcón.', 'После стирки мне нужно развесить бельё на балконе.'],
  ['poner la lavadora', 'запускать стиральную машину', 'Voy a poner la lavadora después de desayunar.', 'Я запущу стиральную машину после завтрака.'],
  ['sacar la basura', 'выносить мусор', 'Me toca sacar la basura esta noche.', 'Сегодня вечером моя очередь выносить мусор.'],
  ['pedir cita', 'записываться на приём', 'Puedes pedir cita con la doctora por teléfono.', 'Ты можешь записаться на приём к врачу по телефону.'],
  ['tomar la temperatura', 'измерять температуру', 'La enfermera va a tomar la temperatura al niño.', 'Медсестра измерит ребёнку температуру.'],
  ['doler la garganta', 'болеть — о горле', 'Me empieza a doler la garganta cuando hablo mucho.', 'У меня начинает болеть горло, когда я много говорю.'],
  ['tener sueño', 'хотеть спать', 'Es normal tener sueño después de un viaje tan largo.', 'Хотеть спать после такой долгой поездки — нормально.'],
  ["parque de atracciones", "парк аттракционов", "El parque de atracciones está abierto hasta las ocho.", "Парк аттракционов открыт до восьми."],
  ['hacer una excursión', 'совершать экскурсионную поездку', 'El domingo vamos a hacer una excursión a un pueblo de la costa.', 'В воскресенье мы поедем на экскурсию в городок на побережье.'],
];

export const deleA2VocabularyTopic: A2VocabularyTopic = {
  name: deleA2TopicName,
  icon: '🇪🇸',
  entries: rows.map(([es, ru, example, exampleRu], index) => ({
    id: index + 1, es, ru, example, exampleRu,
  })),
};
