import type { VocabularyEntry } from './vocabulary';

type Row = [string, string, string, string, string, string];
const rows: Row[] = [
  ['libro','книга','He dejado el libro sobre la mesa.','Я оставил книгу на столе.','Este libro tiene ejercicios muy útiles.','В этой книге есть очень полезные упражнения.'],
  ['dinero','деньги','No llevo dinero en efectivo.','У меня нет с собой наличных денег.','Estoy ahorrando dinero para el viaje.','Я коплю деньги на поездку.'],
  ['caso','случай','En este caso, es mejor esperar.','В этом случае лучше подождать.','La policía está investigando el caso.','Полиция расследует дело.'],
  ['vaso','стакан','¿Me das un vaso de agua?','Дашь мне стакан воды?','El vaso está en la cocina.','Стакан находится на кухне.'],
  ['cosa','вещь','Tengo una cosa importante que contarte.','Мне нужно рассказать тебе одну важную вещь.','Deja tus cosas junto a la puerta.','Оставь свои вещи у двери.'],
  ['palabra','слово','No entiendo esta palabra.','Я не понимаю это слово.','Busca la palabra en el diccionario.','Поищи это слово в словаре.'],
  ['casa','дом','Buscamos una casa cerca del centro.','Мы ищем дом недалеко от центра.','Después del trabajo vuelvo a casa.','После работы я возвращаюсь домой.'],
  ['mesa','стол','La cena ya está en la mesa.','Ужин уже на столе.','Nos sentamos alrededor de la mesa.','Мы сели вокруг стола.'],
  ['día','день','Hoy ha sido un día muy largo.','Сегодня был очень долгий день.','Nos vemos el día veinte.','Увидимся двадцатого числа.'],
  ['clima','климат','El clima de esta región es seco.','Климат этого региона сухой.','Busco un lugar con un clima más suave.','Я ищу место с более мягким климатом.'],
  ['problema','проблема','Tenemos un problema con la reserva.','У нас проблема с бронированием.','No hay problema, puedo esperar.','Нет проблем, я могу подождать.'],
  ['pijama','пижама','El niño ya se ha puesto el pijama.','Ребёнок уже надел пижаму.','Necesito un pijama más abrigado.','Мне нужна более тёплая пижама.'],
  ['tema','тема','Es un tema importante para todos.','Это важная тема для всех.','Prefiero cambiar de tema.','Я предпочитаю сменить тему.'],
  ['idioma','язык','¿Qué idioma hablan en casa?','На каком языке они говорят дома?','Aprender un idioma requiere constancia.','Изучение языка требует регулярности.'],
  ['mapa','карта','Mira la dirección en el mapa.','Посмотри адрес на карте.','El hotel aparece en este mapa.','Отель отмечен на этой карте.'],
  ['mano','рука','Levanta la mano si tienes una pregunta.','Подними руку, если у тебя есть вопрос.','Lleva el bolso en la mano.','Она несёт сумку в руке.'],
  ['radio','радио','He oído la noticia en la radio.','Я услышал новость по радио.','La radio del coche no funciona.','Радио в машине не работает.'],
  ['foto','фотография','¿Puedes hacernos una foto?','Можешь нас сфотографировать?','Tengo esa foto en el móvil.','Эта фотография есть у меня в телефоне.'],
  ['fotografía','фотография','La fotografía salió muy nítida.','Фотография получилась очень чёткой.','Estudia fotografía en Madrid.','Она изучает фотографию в Мадриде.'],
  ['moto','мотоцикл','Va al trabajo en moto.','Он ездит на работу на мотоцикле.','Dejé la moto delante de casa.','Я оставил мотоцикл перед домом.'],
  ['motocicleta','мотоцикл','Lleva casco cuando conduce la motocicleta.','Он надевает шлем, когда едет на мотоцикле.','La motocicleta necesita gasolina.','Мотоциклу нужен бензин.'],
  ['masaje','массаж','He reservado un masaje para esta tarde.','Я записался на массаж на сегодня после обеда.','Este masaje ayuda a relajar la espalda.','Этот массаж помогает расслабить спину.'],
  ['paisaje','пейзаж','Desde aquí se ve un paisaje precioso.','Отсюда виден прекрасный пейзаж.','El paisaje cambia al llegar a la costa.','Пейзаж меняется при приближении к побережью.'],
  ['ciudad','город','Vivo en una ciudad pequeña.','Я живу в небольшом городе.','La ciudad está bien comunicada.','В городе хорошее транспортное сообщение.'],
  ['edad','возраст','La edad no aparece en el formulario.','Возраст не указан в анкете.','Los niños de esa edad aprenden muy rápido.','Дети такого возраста учатся очень быстро.'],
  ['profesión','профессия','¿Cuál es tu profesión?','Какая у тебя профессия?','Eligió una profesión relacionada con la salud.','Она выбрала профессию, связанную со здравоохранением.'],
  ['dirección','адрес','Escribe aquí tu dirección.','Напиши здесь свой адрес.','No encuentro esta dirección en el mapa.','Я не нахожу этот адрес на карте.'],
  ['café','кофе','Tomo café sin azúcar.','Я пью кофе без сахара.','Quedamos para tomar un café.','Мы договорились встретиться за чашкой кофе.'],
  ['espíritu','дух','El equipo mantiene un buen espíritu de colaboración.','В команде сохраняется хороший дух сотрудничества.','La música refleja el espíritu de la época.','Музыка отражает дух эпохи.'],
  ['nombre','имя','¿Cómo se escribe tu nombre?','Как пишется твоё имя?','La reserva está a mi nombre.','Бронирование оформлено на моё имя.'],
  ['apellido','фамилия','Necesito tu nombre y tu apellido.','Мне нужны твоё имя и фамилия.','Su apellido lleva tilde.','В его фамилии есть знак ударения.'],
  ['amor','любовь','Lo hizo por amor a su familia.','Он сделал это из любви к своей семье.','Su historia de amor empezó en la universidad.','Их история любви началась в университете.'],
  ['olor','запах','Me encanta el olor del pan recién hecho.','Мне нравится запах свежеиспечённого хлеба.','Hay un olor extraño en la cocina.','На кухне стоит странный запах.'],
  ['flor','цветок','Hay una flor en la ventana.','На окне стоит цветок.','Le regaló una flor por su cumpleaños.','Он подарил ей цветок на день рождения.'],
  ['amistad','дружба','Nuestra amistad empezó en la escuela.','Наша дружба началась в школе.','Valoro mucho tu amistad.','Я очень ценю твою дружбу.'],
  ['canción','песня','Esta canción me recuerda al verano.','Эта песня напоминает мне о лете.','¿Quién canta esa canción?','Кто исполняет эту песню?'],
  ['ingeniero','инженер','Mi hermano trabaja como ingeniero.','Мой брат работает инженером.','El ingeniero revisó el proyecto.','Инженер проверил проект.'],
  ['ingeniera','женщина-инженер','La ingeniera dirige el equipo técnico.','Женщина-инженер руководит технической командой.','Hablamos con la ingeniera responsable.','Мы поговорили с ответственной женщиной-инженером.'],
  ['maestro','учитель','El maestro explica la tarea con calma.','Учитель спокойно объясняет задание.','Mi abuelo fue maestro de primaria.','Мой дедушка был учителем начальных классов.'],
  ['maestra','учительница','La maestra saluda a sus alumnos.','Учительница приветствует учеников.','Nuestra maestra habla muy claro.','Наша учительница говорит очень понятно.'],
  ['chico','парень','Ese chico estudia conmigo.','Этот парень учится со мной.','El chico de la recepción puede ayudarte.','Парень на стойке регистрации может тебе помочь.'],
  ['chica','девушка','La chica lleva una chaqueta azul.','Девушка одета в синюю куртку.','Conocí a una chica de Sevilla.','Я познакомился с девушкой из Севильи.'],
  ['hermano','брат','Mi hermano vive en Valencia.','Мой брат живёт в Валенсии.','Voy al cine con mi hermano.','Я иду в кино с братом.'],
  ['hermana','сестра','Mi hermana menor estudia medicina.','Моя младшая сестра изучает медицину.','Llamo a mi hermana todos los domingos.','Я звоню сестре каждое воскресенье.'],
  ['paciente','пациент','El paciente espera al médico.','Пациент ждёт врача.','La doctora escucha a cada paciente.','Врач внимательно выслушивает каждого пациента.'],
  ['jefe','начальник','Mi jefe está en una reunión.','Мой начальник на совещании.','El jefe aprobó el nuevo horario.','Начальник утвердил новое расписание.'],
  ['jefa','начальница','La jefa quiere hablar contigo.','Начальница хочет с тобой поговорить.','Nuestra jefa organiza bien el trabajo.','Наша начальница хорошо организует работу.'],
  ['presidente','президент','El presidente dio una rueda de prensa.','Президент провёл пресс-конференцию.','El presidente de la asociación fue elegido ayer.','Президента ассоциации избрали вчера.'],
  ['presidenta','женщина-президент','La presidenta presentó el nuevo programa.','Женщина-президент представила новую программу.','La presidenta de la empresa visitó la oficina.','Президент компании посетила офис.'],
  ['pintor','художник','El pintor trabaja en su estudio.','Художник работает в своей мастерской.','Ese pintor es famoso por sus retratos.','Этот художник известен своими портретами.'],
  ['pintora','художница','La pintora expone sus obras en Madrid.','Художница выставляет свои работы в Мадриде.','Conocimos a una pintora local.','Мы познакомились с местной художницей.'],
  ['profesor','преподаватель','El profesor corrige los ejercicios.','Преподаватель проверяет упражнения.','Mi profesor de español es de Granada.','Мой преподаватель испанского из Гранады.'],
  ['profesora','преподавательница','La profesora explica la gramática.','Преподавательница объясняет грамматику.','Pregúntale a la profesora después de clase.','Спроси преподавательницу после занятия.'],
  ['pianista','пианист','El pianista toca esta noche.','Пианист выступает сегодня вечером.','La pianista ensaya antes del concierto.','Пианистка репетирует перед концертом.'],
  ['estudiante','студент','El estudiante prepara el examen.','Студент готовится к экзамену.','La estudiante vive cerca de la universidad.','Студентка живёт рядом с университетом.'],
  ['padre','отец','Mi padre cocina los domingos.','Мой отец готовит по воскресеньям.','Su padre trabaja desde casa.','Её отец работает из дома.'],
  ['madre','мать','Mi madre llega mañana.','Моя мать приезжает завтра.','Su madre habla tres idiomas.','Его мать говорит на трёх языках.'],
  ['hombre','мужчина','Un hombre pregunta por ti.','Тебя спрашивает мужчина.','El hombre lleva una maleta negra.','Мужчина несёт чёрный чемодан.'],
  ['mujer','женщина','La mujer espera el autobús.','Женщина ждёт автобус.','Una mujer nos indicó el camino.','Одна женщина показала нам дорогу.'],
  ['caballo','конь','El caballo corre por el campo.','Конь бежит по полю.','Aprendió a montar a caballo.','Она научилась ездить верхом.'],
  ['yegua','кобыла','La yegua cuida a su potro.','Кобыла заботится о своём жеребёнке.','Esa yegua es muy tranquila.','Эта кобыла очень спокойная.'],
  ['actor','актёр','El actor interpreta al protagonista.','Актёр играет главного героя.','Conocimos al actor después de la función.','Мы встретили актёра после спектакля.'],
  ['actriz','актриса','La actriz recibió un premio.','Актриса получила награду.','Esa actriz aparece en una serie nueva.','Эта актриса снимается в новом сериале.'],
  ['alcalde','мэр','El alcalde visitó el nuevo hospital.','Мэр посетил новую больницу.','Los vecinos hablaron con el alcalde.','Жители поговорили с мэром.'],
  ['alcaldesa','женщина-мэр','La alcaldesa presentó el proyecto.','Женщина-мэр представила проект.','La alcaldesa se reunió con los vecinos.','Женщина-мэр встретилась с жителями.'],
  ['tigre','тигр','El tigre duerme bajo un árbol.','Тигр спит под деревом.','Vimos un tigre en el parque natural.','Мы увидели тигра в природном парке.'],
  ['tigresa','тигрица','La tigresa protege a sus cachorros.','Тигрица защищает своих детёнышей.','La tigresa salió de la sombra.','Тигрица вышла из тени.'],
  ['país','страна','España es un país muy diverso.','Испания — очень разнообразная страна.','¿De qué país eres?','Из какой ты страны?'],
  ['pared','стена','Hay un cuadro en la pared.','На стене висит картина.','La mesa está junto a la pared.','Стол стоит у стены.'],
  ['israelí','израильтянин','Un estudiante israelí vive en el piso de arriba.','Студент-израильтянин живёт этажом выше.','La periodista israelí habla español.','Израильская журналистка говорит по-испански.'],
  ['tabú','табу','Hablar de dinero sigue siendo un tabú.','Разговор о деньгах по-прежнему остаётся табу.','Ese tema ya no es tabú entre los jóvenes.','Эта тема больше не табу среди молодёжи.'],
  ['luz','свет','Apaga la luz antes de salir.','Выключи свет перед выходом.','Entra mucha luz por la ventana.','Через окно проникает много света.'],
  ['lápiz','карандаш','Escribe la respuesta con lápiz.','Напиши ответ карандашом.','Se me ha caído el lápiz al suelo.','У меня упал карандаш на пол.'],
  ['paraguas','зонт','Lleva el paraguas porque va a llover.','Возьми зонт, потому что будет дождь.','He olvidado el paraguas en el autobús.','Я забыл зонт в автобусе.'],
  ['lunes','понедельник','La clase empieza el lunes.','Занятие начинается в понедельник.','Los lunes trabajo desde casa.','По понедельникам я работаю из дома.'],
  ['crisis','кризис','La empresa atraviesa una crisis.','Компания переживает кризис.','Hablaron de la crisis económica.','Они говорили об экономическом кризисе.'],
  ['amigo','друг','Mi amigo vive cerca de aquí.','Мой друг живёт неподалёку.','Voy a cenar con un amigo.','Я иду ужинать с другом.'],
  ['amiga','подруга','Una amiga me recomendó este café.','Подруга посоветовала мне это кафе.','Mañana viene mi mejor amiga.','Завтра приезжает моя лучшая подруга.'],
  ['agua','вода','Quiero un vaso de agua, por favor.','Я хочу стакан воды, пожалуйста.','El agua está demasiado fría.','Вода слишком холодная.'],
  ['hada','фея','El cuento trata de un hada buena.','Эта сказка о доброй фее.','La niña se disfrazó de hada.','Девочка переоделась феей.'],
  ['alma','душа','La música le llega al alma.','Музыка трогает его душу.','Es una persona con un alma generosa.','Это человек с щедрой душой.'],
  ['artículo','статья','He leído un artículo sobre Madrid.','Я прочитал статью о Мадриде.','El artículo se publicó ayer.','Статья была опубликована вчера.'],
  ['trabajo','работа','Tengo mucho trabajo esta semana.','На этой неделе у меня много работы.','¿Qué tal el trabajo nuevo?','Как новая работа?'],
  ['vida','жизнь','La vida en este barrio es tranquila.','Жизнь в этом районе спокойная.','Quiere cambiar de vida.','Он хочет изменить свою жизнь.'],
  ['familia','семья','Mi familia vive en otra ciudad.','Моя семья живёт в другом городе.','Pasamos el domingo con la familia.','Мы провели воскресенье с семьёй.'],
  ['hijo','сын','Su hijo empieza la escuela este año.','Её сын начинает ходить в школу в этом году.','Tengo un hijo de seis años.','У меня есть шестилетний сын.'],
  ['pariente','родственник','Un pariente viene a visitarnos.','К нам приезжает родственник.','No tengo parientes en esta ciudad.','У меня нет родственников в этом городе.'],
  ['turista','турист','Un turista pidió ayuda en la estación.','Турист попросил помощи на вокзале.','La turista buscaba un hotel barato.','Туристка искала недорогой отель.'],
  ['bolígrafo','шариковая ручка','¿Me prestas un bolígrafo?','Одолжишь мне шариковую ручку?','Firma el documento con bolígrafo azul.','Подпиши документ синей шариковой ручкой.'],
  ['revista','журнал','Compré una revista en el aeropuerto.','Я купил журнал в аэропорту.','La entrevista aparece en esta revista.','Интервью опубликовано в этом журнале.'],
  ['semana','неделя','Esta semana tengo dos exámenes.','На этой неделе у меня два экзамена.','Nos vamos de viaje una semana.','Мы уезжаем в путешествие на неделю.'],
  ['novio','парень','Su novio trabaja en un banco.','Её парень работает в банке.','Voy a cenar con mi novio.','Я иду ужинать со своим парнем.'],
  ['novia','девушка','Mi novia estudia arquitectura.','Моя девушка изучает архитектуру.','Vino a la fiesta con su novia.','Он пришёл на вечеринку со своей девушкой.'],
  ['coche','машина','Dejé el coche en el aparcamiento.','Я оставил машину на парковке.','Vamos al centro en coche.','Мы едем в центр на машине.'],
  ['estudios','учёба','Terminó sus estudios el año pasado.','Он закончил учёбу в прошлом году.','Compagina el trabajo con los estudios.','Она совмещает работу с учёбой.'],
  ['noche','ночь','Esta noche cenamos fuera.','Сегодня вечером мы ужинаем не дома.','No dormí bien durante la noche.','Я плохо спал ночью.'],
  ['¿qué tal?','как дела?','Hola, ¿qué tal?','Привет, как дела?','¿Qué tal tu nuevo trabajo?','Как твоя новая работа?'],
  ['muy bien','очень хорошо','Todo ha salido muy bien.','Всё прошло очень хорошо.','Estoy muy bien, gracias.','У меня всё очень хорошо, спасибо.'],
  ['bien','хорошо','Habla español bastante bien.','Он довольно хорошо говорит по-испански.','Estoy bien, no te preocupes.','У меня всё хорошо, не волнуйся.'],
  ['más o menos','более или менее','Entiendo más o menos la explicación.','Я более или менее понимаю объяснение.','El examen salió más o menos bien.','Экзамен прошёл более или менее хорошо.'],
  ['mal','плохо','He dormido mal esta noche.','Я плохо спал этой ночью.','La conexión funciona mal.','Соединение работает плохо.'],
  ['súper','отлично','La fiesta estuvo súper.','Вечеринка прошла отлично.','Todo va súper en el trabajo.','На работе всё идёт отлично.'],
  ['fatal','ужасно','Hoy me siento fatal.','Сегодня я чувствую себя ужасно.','El tráfico está fatal esta mañana.','Сегодня утром на дорогах ужасная ситуация.'],
  ['muy','очень','La película es muy interesante.','Фильм очень интересный.','Vivimos muy cerca del centro.','Мы живём очень близко к центру.'],
  ['bueno','хороший','Es un buen momento para hablar.','Сейчас хороший момент для разговора.','Este restaurante es muy bueno.','Этот ресторан очень хороший.'],
  ['malo','плохой','Hace mal tiempo hoy.','Сегодня плохая погода.','Fue una mala idea salir tan tarde.','Было плохой идеей выходить так поздно.'],
  ['empleado','служащий','El empleado atiende a los clientes.','Служащий обслуживает клиентов.','Pregunta al empleado de información.','Спроси служащего на стойке информации.'],
  ['empleada','служащая','La empleada prepara los documentos.','Служащая готовит документы.','Una empleada nos mostró la oficina.','Служащая показала нам офис.'],
  ['peluquero','парикмахер','El peluquero me cortó el pelo.','Парикмахер подстриг меня.','Mi peluquero trabaja los sábados.','Мой парикмахер работает по субботам.'],
  ['peluquera','парикмахер-женщина','La peluquera tiene una cita libre a las cinco.','У парикмахера есть свободное время в пять часов.','La peluquera le hizo un corte moderno.','Парикмахер сделала ей современную стрижку.'],
  ['intérprete','переводчик','El intérprete traduce la conversación.','Переводчик переводит разговор.','La intérprete trabaja en una conferencia.','Переводчица работает на конференции.'],
  ['camarero','официант','El camarero trae la cuenta.','Официант приносит счёт.','Llamamos al camarero para pedir.','Мы позвали официанта, чтобы сделать заказ.'],
  ['camarera','официантка','La camarera recomienda el plato del día.','Официантка рекомендует блюдо дня.','La camarera nos sirvió el café.','Официантка подала нам кофе.'],
  ['abogado','адвокат','El abogado revisa el contrato.','Адвокат проверяет договор.','Necesito hablar con mi abogado.','Мне нужно поговорить со своим адвокатом.'],
  ['abogada','женщина-адвокат','La abogada explicó nuestros derechos.','Женщина-адвокат объяснила наши права.','Contrataron a una abogada especialista.','Они наняли женщину-адвоката, которая специализируется в этой области.'],
  ['enfermero','медбрат','El enfermero toma la temperatura al paciente.','Медбрат измеряет пациенту температуру.','Pregunta al enfermero de guardia.','Спроси дежурного медбрата.'],
  ['enfermera','медсестра','La enfermera prepara la medicación.','Медсестра готовит лекарства.','Una enfermera nos indicó la habitación.','Медсестра показала нам палату.'],
  ['secretario','секретарь','El secretario organiza la reunión.','Секретарь организует совещание.','Habla con el secretario del director.','Поговори с секретарём директора.'],
  ['secretaria','женщина-секретарь','La secretaria contestó al correo.','Женщина-секретарь ответила на письмо.','La secretaria guarda una copia del documento.','Женщина-секретарь хранит копию документа.'],
  ['periodista','журналист','El periodista prepara una entrevista.','Журналист готовит интервью.','La periodista informó desde Bogotá.','Журналистка вела репортаж из Боготы.'],
  ['escritor','писатель','El escritor presenta su nueva novela.','Писатель представляет свой новый роман.','Conocí al escritor en una feria.','Я познакомился с писателем на ярмарке.'],
  ['escritora','писательница','La escritora firma libros esta tarde.','Писательница подписывает книги сегодня после обеда.','Esa escritora vive en Barcelona.','Эта писательница живёт в Барселоне.'],
  ['cantante','певец','El cantante sale al escenario.','Певец выходит на сцену.','La cantante está grabando un álbum.','Певица записывает альбом.'],
  ['ser','быть','Mi hermana es profesora.','Моя сестра — преподавательница.','Ellos son empleados de este hotel.','Они служащие этого отеля.'],
  ['piso','квартира','Vivimos en un piso cerca del metro.','Мы живём в квартире рядом с метро.','El piso tiene dos dormitorios y un balcón.','В квартире две спальни и балкон.'],
  ['blanco','белый','Lleva una camisa blanca.','На нём белая рубашка.','Pintaron las paredes de blanco.','Они покрасили стены в белый цвет.'],
  ['pequeño','маленький','Buscamos un hotel pequeño y tranquilo.','Мы ищем маленький и тихий отель.','La cocina es pequeña, pero cómoda.','Кухня маленькая, но удобная.'],
  ['gracias','спасибо','Muchas gracias por tu ayuda.','Большое спасибо за твою помощь.','Gracias, ya tengo todo lo que necesito.','Спасибо, у меня уже есть всё необходимое.'],
  ['género','род','En español, cada sustantivo tiene género.','В испанском языке у каждого существительного есть род.','Comprueba el género antes de elegir el artículo.','Проверь род, прежде чем выбирать артикль.'],
  ['número','число','El artículo concuerda en género y número.','Артикль согласуется в роде и числе.','Cambia el sustantivo al número plural.','Поставь существительное во множественное число.'],
  ['sustantivo','существительное','Casa es un sustantivo femenino.','Casa — существительное женского рода.','Subraya el sustantivo de la frase.','Подчеркни существительное в предложении.'],
  ['El Cairo','Каир','El Cairo es la capital de Egipto.','Каир — столица Египта.','Mañana volamos a El Cairo.','Завтра мы летим в Каир.'],
  ['El País','газета «Эль Паис»','Leo El País por la mañana.','Я читаю газету «Эль Паис» по утрам.','El País publicó la entrevista ayer.','Газета «Эль Паис» опубликовала интервью вчера.'],
  ['español','испанский','Estudio español después del trabajo.','Я учу испанский после работы.','Esta palabra es muy común en español.','Это слово очень распространено в испанском языке.'],
];

export const unidad2Vocabulary: VocabularyEntry[] = rows.map(([es,ru,example,exampleRu,extraExample,extraExampleRu], index) => ({
  id: index + 1, es, ru, example, exampleRu, extraExample, extraExampleRu,
}));
