create table if not exists public.user_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_progress enable row level security;

create policy "Users can read their own progress"
  on public.user_progress for select
  using (auth.uid() = user_id);

create policy "Users can create their own progress"
  on public.user_progress for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own progress"
  on public.user_progress for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.create_empty_user_progress()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.user_progress (user_id, data)
  values (new.id, '{}'::jsonb)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_progress on auth.users;
create trigger on_auth_user_created_progress
  after insert on auth.users
  for each row execute procedure public.create_empty_user_progress();

create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  report_key text not null,
  kind text not null check (kind in ('example', 'exercise')),
  section text not null,
  content jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'withdrawn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, report_key)
);

alter table public.content_reports enable row level security;

create policy "Users can read their own reports"
  on public.content_reports for select
  using (auth.uid() = user_id);

create policy "Users can create their own reports"
  on public.content_reports for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own reports"
  on public.content_reports for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
